In [1]:
import pandas as pd

employees = {
    "Employee_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Vikas", "Neha"],
    "Department": ["HR", "IT", "Finance", "IT", "Sales", "HR"],
    "Age": [25, 30, 28, 35, 40, 27],
    "Salary": [35000, 60000, 50000, 75000, 45000, 38000]
}

df = pd.DataFrame(employees)

df

   Employee_ID   Name Department  Age  Salary
0          101   Amit         HR   25   35000
1          102  Priya         IT   30   60000
2          103  Rahul    Finance   28   50000
3          104  Sneha         IT   35   75000
4          105  Vikas      Sales   40   45000
5          106   Neha         HR   27   38000

# 📌 head()

> **Definition:** `head()` is a Pandas method used to display the first few rows of a DataFrame. By default, it returns the first **5 rows**, allowing us to quickly inspect the dataset.

In [2]:
df.head()

   Employee_ID   Name Department  Age  Salary
0          101   Amit         HR   25   35000
1          102  Priya         IT   30   60000
2          103  Rahul    Finance   28   50000
3          104  Sneha         IT   35   75000
4          105  Vikas      Sales   40   45000

In [3]:
df.head(3)

   Employee_ID   Name Department  Age  Salary
0          101   Amit         HR   25   35000
1          102  Priya         IT   30   60000
2          103  Rahul    Finance   28   50000

# 📌 tail()

> **Definition:** `tail()` is a Pandas method used to display the last few rows of a DataFrame. By default, it returns the last **5 rows**, allowing us to inspect the end of the dataset.

In [4]:
df.tail()

   Employee_ID   Name Department  Age  Salary
1          102  Priya         IT   30   60000
2          103  Rahul    Finance   28   50000
3          104  Sneha         IT   35   75000
4          105  Vikas      Sales   40   45000
5          106   Neha         HR   27   38000

In [5]:
df.tail(3)

   Employee_ID   Name Department  Age  Salary
3          104  Sneha         IT   35   75000
4          105  Vikas      Sales   40   45000
5          106   Neha         HR   27   38000

# 📌 info()

> **Definition:** `info()` is a Pandas method that displays a concise summary of a DataFrame, including the number of rows, column names, data types, non-null values, and memory usage.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  6 non-null      int64
 1   Name         6 non-null      object
 2   Department   6 non-null      object
 3   Age          6 non-null      int64
 4   Salary       6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes

# 📌 describe()

> **Definition:** `describe()` is a Pandas method that generates descriptive statistics for numerical columns in a DataFrame, such as count, mean, standard deviation, minimum, maximum, and quartile values.

In [7]:
df.describe()

       Employee_ID        Age        Salary
count     6.000000   6.000000      6.000000
mean    103.500000  30.833333  50500.000000
std       1.870829   5.636193  14949.916388
min     101.000000  25.000000  35000.000000
25%     102.250000  27.250000  39750.000000
50%     103.500000  29.000000  47500.000000
75%     104.750000  33.750000  57500.000000
max     106.000000  40.000000  75000.000000

In [17]:
#For Single Element
print("Average Age :", df["Age"].mean())  
print("Maximum Age :", df["Age"].max())
print("Minimum Age :", df["Age"].min())

Average Age : 30.833333333333332
Maximum Age : 40
Minimum Age : 25

# 📌 shape

> **Definition:** `shape` is a Pandas DataFrame attribute that returns the dimensions of a DataFrame as a tuple in the form **(number of rows, number of columns)**.

In [22]:
print(df.shape)
print(df.shape[0])
print(df.shape[1])

(6, 5)
6
5

# 📌 columns

> **Definition:** `columns` is a Pandas DataFrame attribute that returns the names (labels) of all columns in a DataFrame as an Index object.

In [23]:
print(df.columns)

Index(['Employee_ID', 'Name', 'Department', 'Age', 'Salary'], dtype='object')

In [24]:
print(df.columns.tolist())

['Employee_ID', 'Name', 'Department', 'Age', 'Salary']

# 📌 index

> **Definition:** `index` is a Pandas DataFrame attribute that returns the row labels (indexes) of a DataFrame as an Index object. By default, Pandas assigns indexes starting from **0**.

In [29]:
print(df.index)

RangeIndex(start=0, stop=6, step=1)

In [28]:
print(df.index.tolist())

[0, 1, 2, 3, 4, 5]

In [31]:
df.index[-1]

5

# 📌 dtypes

> **Definition:** `dtypes` is a Pandas DataFrame attribute that displays the data type of each column in a DataFrame. It helps us identify whether a column contains integers, floating-point numbers, text, boolean values, dates, or other data types.

In [37]:
print(df.dtypes)

Employee_ID     int64
Name           object
Department     object
Age             int64
Salary          int64
dtype: object

In [39]:
print(df[["Name","Age"]].dtypes)

Name    object
Age      int64
dtype: object