In [1]:
import pandas as pd

employees = {
    "Employee_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Vikas", "Neha"],
    "Department": ["HR", "IT", "Finance", "IT", "Sales", "HR"],
    "Age": [25, 30, 28, 35, 40, 27],
    "Salary": [35000, 60000, 50000, 75000, 45000, 38000]
}

df = pd.DataFrame(employees)

df

   Employee_ID   Name Department  Age  Salary
0          101   Amit         HR   25   35000
1          102  Priya         IT   30   60000
2          103  Rahul    Finance   28   50000
3          104  Sneha         IT   35   75000
4          105  Vikas      Sales   40   45000
5          106   Neha         HR   27   38000

# 📌 Selecting a Single Column

> **Definition:** Selecting a single column means retrieving one specific column from a DataFrame. In Pandas, this is done by passing the column name inside a single pair of square brackets (`[]`).

In [2]:
#syntax:-  df["Column Name"]
df["Name"]

0     Amit
1    Priya
2    Rahul
3    Sneha
4    Vikas
5     Neha
Name: Name, dtype: object

In [3]:
df["Salary"]

0    35000
1    60000
2    50000
3    75000
4    45000
5    38000
Name: Salary, dtype: int64

In [4]:
print(df["Salary"].mean())
print(df["Age"].max())
print(df["Name"].count())

50500.0
40
6

# 📌 Selecting Multiple Columns

> **Definition:** Selecting multiple columns means retrieving two or more columns from a DataFrame. In Pandas, this is done by passing a **list of column names** inside **double square brackets (`[[]]`)**.

In [5]:
# Syntax:-  df[["Column1", "Column2", "Column3"]]
print(df[["Age","Salary"]])
print(df[["Age","Salary"]].mean())

   Age  Salary
0   25   35000
1   30   60000
2   28   50000
3   35   75000
4   40   45000
5   27   38000
Age          30.833333
Salary    50500.000000
dtype: float64

# 📌 Selecting Rows using Slicing

> **Definition:** Row slicing is the process of selecting a range of rows from a DataFrame using Python slicing syntax (`start:stop`). The start index is included, while the stop index is excluded.

In [6]:
# Syntax:- df[start:stop]
print(df[1:4])
print(df[:3])
print(df[3:])

   Employee_ID   Name Department  Age  Salary
1          102  Priya         IT   30   60000
2          103  Rahul    Finance   28   50000
3          104  Sneha         IT   35   75000
   Employee_ID   Name Department  Age  Salary
0          101   Amit         HR   25   35000
1          102  Priya         IT   30   60000
2          103  Rahul    Finance   28   50000
   Employee_ID   Name Department  Age  Salary
3          104  Sneha         IT   35   75000
4          105  Vikas      Sales   40   45000
5          106   Neha         HR   27   38000

# 📌 loc[] – Label-Based Indexing

> **Definition:** `loc[]` is a Pandas indexer used to select rows and columns by their **labels (index names and column names)**. Unlike Python slicing, **the stop label is included** in `loc[]`.

In [7]:
# Syntax:-  df.loc[row_selection, column_selection]
print(df.loc[2])

Employee_ID        103
Name             Rahul
Department     Finance
Age                 28
Salary           50000
Name: 2, dtype: object

In [8]:
print(df.loc[1:4])  # loc[] includes stop value whereas slicing don't include it.

   Employee_ID   Name Department  Age  Salary
1          102  Priya         IT   30   60000
2          103  Rahul    Finance   28   50000
3          104  Sneha         IT   35   75000
4          105  Vikas      Sales   40   45000

In [9]:
print(df.loc[:,["Name","Salary"]])

    Name  Salary
0   Amit   35000
1  Priya   60000
2  Rahul   50000
3  Sneha   75000
4  Vikas   45000
5   Neha   38000

In [10]:
print(df.loc[1:4, ["Name", "Salary"]])

    Name  Salary
1  Priya   60000
2  Rahul   50000
3  Sneha   75000
4  Vikas   45000

# 📌 iloc[] – Position-Based Indexing

> **Definition:** `iloc[]` is a Pandas indexer used to select rows and columns based on their **integer positions**. It follows Python slicing rules, where the **start position is included** and the **stop position is excluded**.

In [11]:
# Syntax:- df.iloc[row_selection, column_selection]
print(df.iloc[3])

Employee_ID      104
Name           Sneha
Department        IT
Age               35
Salary         75000
Name: 3, dtype: object

In [12]:
print(df.iloc[2])

Employee_ID        103
Name             Rahul
Department     Finance
Age                 28
Salary           50000
Name: 2, dtype: object

In [13]:
print(df.iloc[1:4])

   Employee_ID   Name Department  Age  Salary
1          102  Priya         IT   30   60000
2          103  Rahul    Finance   28   50000
3          104  Sneha         IT   35   75000

In [14]:
print(df.iloc[:,[1,4]])

    Name  Salary
0   Amit   35000
1  Priya   60000
2  Rahul   50000
3  Sneha   75000
4  Vikas   45000
5   Neha   38000

In [15]:
print(df.iloc[1:4, [1, 4]])

    Name  Salary
1  Priya   60000
2  Rahul   50000
3  Sneha   75000

In [16]:
df.iloc[1:4, 0:2]

   Employee_ID   Name
1          102  Priya
2          103  Rahul
3          104  Sneha

# 📌 Boolean Indexing (Filtering Data)

> **Definition:** Boolean Indexing is the process of selecting rows from a DataFrame based on one or more conditions. It returns only the rows where the condition evaluates to **True**.

In [17]:
# Syntax:-   df[condition]
print(df[df["Salary"]>50000])
print(df[df["Age"]>30])
print(df[df["Age"]<30])

   Employee_ID   Name Department  Age  Salary
1          102  Priya         IT   30   60000
3          104  Sneha         IT   35   75000
   Employee_ID   Name Department  Age  Salary
3          104  Sneha         IT   35   75000
4          105  Vikas      Sales   40   45000
   Employee_ID   Name Department  Age  Salary
0          101   Amit         HR   25   35000
2          103  Rahul    Finance   28   50000
5          106   Neha         HR   27   38000

In [18]:
print(df[df["Department"] == "IT"])

   Employee_ID   Name Department  Age  Salary
1          102  Priya         IT   30   60000
3          104  Sneha         IT   35   75000

In [19]:
print(df[(df["Salary"] > 40000) & (df["Age"] < 35)])

   Employee_ID   Name Department  Age  Salary
1          102  Priya         IT   30   60000
2          103  Rahul    Finance   28   50000

In [20]:
print(df[(df["Department"] == "HR") | (df["Department"] == "Sales")])

   Employee_ID   Name Department  Age  Salary
0          101   Amit         HR   25   35000
4          105  Vikas      Sales   40   45000
5          106   Neha         HR   27   38000

# 📌 Selecting Columns using Dot Notation (`df.ColumnName`)

> **Definition:** Dot notation is a shortcut for selecting a single column from a DataFrame by writing the column name after a dot (`.`). It can only be used when the column name is a valid Python identifier.

In [21]:
#Syntax:- df.ColumnName
print(df.Name)

0     Amit
1    Priya
2    Rahul
3    Sneha
4    Vikas
5     Neha
Name: Name, dtype: object

In [22]:
print(df.Employee ID)
# this willl produce an error as it is not a valid python identifier so we should
#try to not use this method much

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2459032405.py, line 1)

# 📌 at[] – Accessing a Single Value

> **Definition:** `at[]` is a Pandas indexer used to access or update a **single value** in a DataFrame using a **row label** and a **column name**. It is faster than `loc[]` when working with only one cell.

In [ ]:
# Syntax:- df.at[row_label, column_name]
print(df.at[3,"Salary"]) #Gives salary at index 3rd

In [ ]:
df.at[4, "Department"]

In [23]:
# at[] also modifies a single value 
df.at[2,"Salary"]= 55000
print(df)

   Employee_ID   Name Department  Age  Salary
0          101   Amit         HR   25   35000
1          102  Priya         IT   30   60000
2          103  Rahul    Finance   28   55000
3          104  Sneha         IT   35   75000
4          105  Vikas      Sales   40   45000
5          106   Neha         HR   27   38000

# 📌 iat[] – Accessing a Single Value by Position

> **Definition:** `iat[]` is a Pandas indexer used to access or update a **single value** in a DataFrame using the **integer position** of the row and column. It is optimized for fast access to one specific cell by position.

In [26]:
# Syntax:- df.iat[row_position, column_position]
print(df.iat[3,4])

75000

In [27]:
print(df.iat[4, 2])

Sales

In [29]:
df.iat[2, 4] = 50000
print(df)

   Employee_ID   Name Department  Age  Salary
0          101   Amit         HR   25   35000
1          102  Priya         IT   30   60000
2          103  Rahul    Finance   28   50000
3          104  Sneha         IT   35   75000
4          105  Vikas      Sales   40   45000
5          106   Neha         HR   27   38000

## 📊 Comparison of `loc[]`, `iloc[]`, `at[]`, and `iat[]`

| Feature | `loc[]` | `iloc[]` | `at[]` | `iat[]` |
|---------|---------|----------|---------|----------|
| **Selection Based On** | Labels | Integer Positions | Labels | Integer Positions |
| **Row Selection** | ✅ Yes | ✅ Yes | ❌ Single Row Only | ❌ Single Row Only |
| **Column Selection** | ✅ Yes | ✅ Yes | ❌ Single Column Only | ❌ Single Column Only |
| **Multiple Rows** | ✅ Yes | ✅ Yes | ❌ No | ❌ No |
| **Multiple Columns** | ✅ Yes | ✅ Yes | ❌ No | ❌ No |
| **Single Value** | ✅ Yes | ✅ Yes | ✅ Optimized | ✅ Optimized |
| **Update Values** | ✅ Yes | ✅ Yes | ✅ Yes | ✅ Yes |
| **Faster for One Cell** | ❌ No | ❌ No | ✅ Yes | ✅ Yes |

---

## 📝 Syntax Comparison

| Indexer | Syntax | Example |
|---------|--------|---------|
| `loc[]` | `df.loc[row_label, column_name]` | `df.loc[2, "Salary"]` |
| `iloc[]` | `df.iloc[row_position, column_position]` | `df.iloc[2, 4]` |
| `at[]` | `df.at[row_label, column_name]` | `df.at[2, "Salary"]` |
| `iat[]` | `df.iat[row_position, column_position]` | `df.iat[2, 4]` |

---

## 🎯 Which One Should You Use?

| Situation | Recommended Indexer |
|-----------|---------------------|
| Select multiple rows/columns using **labels** | `loc[]` |
| Select multiple rows/columns using **positions** | `iloc[]` |
| Access or update **one value** using **labels** | `at[]` |
| Access or update **one value** using **positions** | `iat[]` |

---

## 🧠 Quick Memory Trick

| Indexer | Remember |
|---------|----------|
| `loc[]` | **L = Labels** |
| `iloc[]` | **I = Integer Locations** |
| `at[]` | **A single value using Labels** |
| `iat[]` | **Integer position of A single value** |