## Basic Condition Filtering

**Definition:**
Basic condition filtering selects only those rows that satisfy a given condition.

**Syntax:**
dataframe[condition]

In [1]:
import pandas as pd

employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan"],
    "Department": ["HR", "IT", "Sales", "IT", "Finance"],
    "Salary": [45000, 70000, 55000, 80000, 60000]
})

employees

  Employee Department  Salary
0     Amit         HR   45000
1     Neha         IT   70000
2    Rahul      Sales   55000
3    Priya         IT   80000
4    Karan    Finance   60000

In [2]:
high_salary=employees[employees["Salary"]> 60000]
high_salary

  Employee Department  Salary
1     Neha         IT   70000
3    Priya         IT   80000

In [5]:
print(employees[employees["Salary"] != 60000])

  Employee Department  Salary
0     Amit         HR   45000
1     Neha         IT   70000
2    Rahul      Sales   55000
3    Priya         IT   80000

In [6]:
print(employees[employees["Department"]=="IT"])

  Employee Department  Salary
1     Neha         IT   70000
3    Priya         IT   80000

## Multiple Condition Filtering

**Definition:**
Multiple condition filtering selects rows that satisfy two or more conditions at the same time.

**Syntax:**
dataframe[(condition1) & (condition2)]

dataframe[(condition1) | (condition2)]

dataframe[~condition]

In [7]:
import pandas as pd

employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan", "Sneha"],
    "Department": ["HR", "IT", "Sales", "IT", "Finance", "IT"],
    "Salary": [45000, 70000, 55000, 80000, 60000, 50000],
    "Experience": [2, 5, 3, 7, 4, 1]
})

employees

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
1     Neha         IT   70000           5
2    Rahul      Sales   55000           3
3    Priya         IT   80000           7
4    Karan    Finance   60000           4
5    Sneha         IT   50000           1

In [8]:
print(employees[(employees["Department"]=="IT")&(employees["Salary"]>60000)])

  Employee Department  Salary  Experience
1     Neha         IT   70000           5
3    Priya         IT   80000           7

In [10]:
print(employees[(employees["Department"]=="HR")|(employees["Department"]=="Finance")])

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
4    Karan    Finance   60000           4

In [19]:
print(employees[~(employees["Department"]=="IT")])

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
2    Rahul      Sales   55000           3
4    Karan    Finance   60000           4

## isin()

**Definition:**
Checks whether each value in a column exists in a given list of values.

**Syntax:**
dataframe[dataframe["column"].isin([value1, value2, ...])]

In [21]:
import pandas as pd

employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan", "Sneha"],
    "Department": ["HR", "IT", "Sales", "IT", "Finance", "IT"],
    "Salary": [45000, 70000, 55000, 80000, 60000, 50000]
})

employees

  Employee Department  Salary
0     Amit         HR   45000
1     Neha         IT   70000
2    Rahul      Sales   55000
3    Priya         IT   80000
4    Karan    Finance   60000
5    Sneha         IT   50000

In [22]:
print(employees[employees["Department"].isin(["IT","HR"])])

  Employee Department  Salary
0     Amit         HR   45000
1     Neha         IT   70000
3    Priya         IT   80000
5    Sneha         IT   50000

In [23]:
print(employees[employees["Salary"].isin([45000,70000])])

  Employee Department  Salary
0     Amit         HR   45000
1     Neha         IT   70000

In [24]:
print(employees[employees["Employee"].isin(["Amit","Priya","Sneha"])])

  Employee Department  Salary
0     Amit         HR   45000
3    Priya         IT   80000
5    Sneha         IT   50000

In [25]:
print(employees[~(employees["Department"].isin(["IT"]))])

  Employee Department  Salary
0     Amit         HR   45000
2    Rahul      Sales   55000
4    Karan    Finance   60000

## between()

**Definition:**
Checks whether values lie between two specified values.

**Syntax:**
dataframe[dataframe["column"].between(start_value, end_value)]

In [27]:
import pandas as pd

employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan", "Sneha"],
    "Department": ["HR", "IT", "Sales", "IT", "Finance", "IT"],
    "Salary": [45000, 70000, 55000, 80000, 60000, 50000]
})

employees

  Employee Department  Salary
0     Amit         HR   45000
1     Neha         IT   70000
2    Rahul      Sales   55000
3    Priya         IT   80000
4    Karan    Finance   60000
5    Sneha         IT   50000

In [29]:
print(employees[employees["Salary"].between(50000,70000)])

  Employee Department  Salary
1     Neha         IT   70000
2    Rahul      Sales   55000
4    Karan    Finance   60000
5    Sneha         IT   50000

In [32]:
employees["Experience"]=[2,5,3,7,4,1]
print(employees)

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
1     Neha         IT   70000           5
2    Rahul      Sales   55000           3
3    Priya         IT   80000           7
4    Karan    Finance   60000           4
5    Sneha         IT   50000           1

In [34]:
print(employees[employees["Experience"].between(2,5)])

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
1     Neha         IT   70000           5
2    Rahul      Sales   55000           3
4    Karan    Finance   60000           4

In [35]:
print(employees[employees["Employee"].between("K", "R")])

  Employee Department  Salary  Experience
1     Neha         IT   70000           5
3    Priya         IT   80000           7
4    Karan    Finance   60000           4

## query()

**Definition:**
Filters rows by evaluating a condition written as a string.

**Syntax:**
dataframe.query("condition")

In [36]:
import pandas as pd

employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan", "Sneha"],
    "Department": ["HR", "IT", "Sales", "IT", "Finance", "IT"],
    "Salary": [45000, 70000, 55000, 80000, 60000, 50000],
    "Experience": [2, 5, 3, 7, 4, 1]
})

employees

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
1     Neha         IT   70000           5
2    Rahul      Sales   55000           3
3    Priya         IT   80000           7
4    Karan    Finance   60000           4
5    Sneha         IT   50000           1

In [38]:
print(employees.query("Salary >60000"))

  Employee Department  Salary  Experience
1     Neha         IT   70000           5
3    Priya         IT   80000           7

In [39]:
print(employees.query("Department == 'IT' and Salary > 60000"))

  Employee Department  Salary  Experience
1     Neha         IT   70000           5
3    Priya         IT   80000           7

In [40]:
print(employees.query("Salary >= 55000 and Experience > 3"))

  Employee Department  Salary  Experience
1     Neha         IT   70000           5
3    Priya         IT   80000           7
4    Karan    Finance   60000           4

In [41]:
minimum_salary = 60000
print(employees.query("Salary > @minimum_salary"))

  Employee Department  Salary  Experience
1     Neha         IT   70000           5
3    Priya         IT   80000           7

The @ symbol tells query() to use the value of a Python variable.

Without @, Pandas will search for a column named minimum_salary.