## sort_values()

**Definition:**
Sorts the rows of a DataFrame based on the values of one or more columns.

**Syntax:**
dataframe.sort_values(by="column_name")

In [1]:
import pandas as pd

employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan"],
    "Department": ["HR", "IT", "Sales", "IT", "Finance"],
    "Salary": [45000, 70000, 55000, 80000, 60000],
    "Experience": [2, 5, 3, 7, 4]
})

employees

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
1     Neha         IT   70000           5
2    Rahul      Sales   55000           3
3    Priya         IT   80000           7
4    Karan    Finance   60000           4

In [2]:
print(employees.sort_values(by="Salary"))

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
2    Rahul      Sales   55000           3
4    Karan    Finance   60000           4
1     Neha         IT   70000           5
3    Priya         IT   80000           7

## ascending Parameter

**Definition:**
Controls the sorting order in `sort_values()`. It can sort data in ascending or descending order.

**Syntax:**
dataframe.sort_values(by="column_name", ascending=True)

dataframe.sort_values(by="column_name", ascending=False)

In [3]:
import pandas as pd
employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan"],
    "Department": ["HR", "IT", "Sales", "IT", "Finance"],
    "Salary": [45000, 70000, 55000, 80000, 60000],
    "Experience": [2, 5, 3, 7, 4]
})
employees

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
1     Neha         IT   70000           5
2    Rahul      Sales   55000           3
3    Priya         IT   80000           7
4    Karan    Finance   60000           4

In [11]:
print(employees.sort_values(by="Salary",ascending=True))
print("\n",employees.sort_values(by="Salary",ascending=False))

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
2    Rahul      Sales   55000           3
4    Karan    Finance   60000           4
1     Neha         IT   70000           5
3    Priya         IT   80000           7

   Employee Department  Salary  Experience
3    Priya         IT   80000           7
1     Neha         IT   70000           5
4    Karan    Finance   60000           4
2    Rahul      Sales   55000           3
0     Amit         HR   45000           2

In [14]:
print(employees.sort_values(by="Employee",ascending=False))

  Employee Department  Salary  Experience
2    Rahul      Sales   55000           3
3    Priya         IT   80000           7
1     Neha         IT   70000           5
4    Karan    Finance   60000           4
0     Amit         HR   45000           2

In [15]:
print(employees.sort_values(by="Experience",ascending=False))

  Employee Department  Salary  Experience
3    Priya         IT   80000           7
1     Neha         IT   70000           5
4    Karan    Finance   60000           4
2    Rahul      Sales   55000           3
0     Amit         HR   45000           2

## Sorting by Multiple Columns

**Definition:**
Sorts a DataFrame using two or more columns in a specified order.

**Syntax:**
dataframe.sort_values(by=["column1", "column2"])

dataframe.sort_values(
    by=["column1", "column2"],
    ascending=[True, False]
)

In [17]:
import pandas as pd
employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan", "Sneha"],
    "Department": ["HR", "IT", "Sales", "IT", "Finance", "IT"],
    "Salary": [45000, 70000, 55000, 80000, 60000, 50000],
    "Experience": [2, 5, 3, 7, 4, 1]
})
employees

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
1     Neha         IT   70000           5
2    Rahul      Sales   55000           3
3    Priya         IT   80000           7
4    Karan    Finance   60000           4
5    Sneha         IT   50000           1

In [18]:
print(employees.sort_values(by=["Department","Salary"]))

  Employee Department  Salary  Experience
4    Karan    Finance   60000           4
0     Amit         HR   45000           2
5    Sneha         IT   50000           1
1     Neha         IT   70000           5
3    Priya         IT   80000           7
2    Rahul      Sales   55000           3

In [19]:
print(employees.sort_values(
    by=["Department", "Salary"],
    ascending=[True, False]
))

  Employee Department  Salary  Experience
4    Karan    Finance   60000           4
0     Amit         HR   45000           2
3    Priya         IT   80000           7
1     Neha         IT   70000           5
5    Sneha         IT   50000           1
2    Rahul      Sales   55000           3

In [20]:
print(employees.sort_values(by=["Department","Experience"],ascending=[True,True]))

  Employee Department  Salary  Experience
4    Karan    Finance   60000           4
0     Amit         HR   45000           2
5    Sneha         IT   50000           1
1     Neha         IT   70000           5
3    Priya         IT   80000           7
2    Rahul      Sales   55000           3

## sort_index()

**Definition:**
Sorts a DataFrame based on its index labels.

**Syntax:**
dataframe.sort_index()

dataframe.sort_index(ascending=False)

In [21]:
import pandas as pd
employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan"],
    "Department": ["HR", "IT", "Sales", "IT", "Finance"],
    "Salary": [45000, 70000, 55000, 80000, 60000]
})
employees

  Employee Department  Salary
0     Amit         HR   45000
1     Neha         IT   70000
2    Rahul      Sales   55000
3    Priya         IT   80000
4    Karan    Finance   60000

In [22]:
sorted_salary=employees.sort_values(by="Salary")
sorted_salary

  Employee Department  Salary
0     Amit         HR   45000
2    Rahul      Sales   55000
4    Karan    Finance   60000
1     Neha         IT   70000
3    Priya         IT   80000

## sort_index()

**Definition:**
Sorts a DataFrame based on its index labels.

**Syntax:**
dataframe.sort_index()

dataframe.sort_index(ascending=False)

In [23]:
import pandas as pd
employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan"],
    "Department": ["HR", "IT", "Sales", "IT", "Finance"],
    "Salary": [45000, 70000, 55000, 80000, 60000]
})
employees

  Employee Department  Salary
0     Amit         HR   45000
1     Neha         IT   70000
2    Rahul      Sales   55000
3    Priya         IT   80000
4    Karan    Finance   60000

In [24]:
sorted_salary.sort_index()

  Employee Department  Salary
0     Amit         HR   45000
1     Neha         IT   70000
2    Rahul      Sales   55000
3    Priya         IT   80000
4    Karan    Finance   60000

In [25]:
employees.sort_index(ascending=False)

  Employee Department  Salary
4    Karan    Finance   60000
3    Priya         IT   80000
2    Rahul      Sales   55000
1     Neha         IT   70000
0     Amit         HR   45000