## isna()

**Definition:**
Checks whether each value in a DataFrame or Series is a missing value (`NaN`).

**Syntax:**
dataframe.isna()

series.isna()

In [1]:
import pandas as pd
import numpy as np

employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan"],
    "Department": ["HR", "IT", np.nan, "IT", "Finance"],
    "Salary": [45000, np.nan, 55000, 80000, np.nan],
    "Experience": [2, 5, 3, np.nan, 4]
})

employees

  Employee Department   Salary  Experience
0     Amit         HR  45000.0         2.0
1     Neha         IT      NaN         5.0
2    Rahul        NaN  55000.0         3.0
3    Priya         IT  80000.0         NaN
4    Karan    Finance      NaN         4.0

In [2]:
print(employees.isna())

   Employee  Department  Salary  Experience
0     False       False   False       False
1     False       False    True       False
2     False        True   False       False
3     False       False   False        True
4     False       False    True       False

In [11]:
print(employees[employees["Salary"].isna()])

  Employee Department  Salary  Experience
1     Neha         IT     NaN         5.0
4    Karan    Finance     NaN         4.0

In [6]:
employees.isna().sum() #Find the total number of missing values in each column.

Employee      0
Department    1
Salary        2
Experience    1
dtype: int64

## notna()

**Definition:**
Checks whether each value in a DataFrame or Series is **not** a missing value (`NaN`).

**Syntax:**
dataframe.notna()

series.notna()

In [8]:
import pandas as pd
import numpy as np

employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan"],
    "Department": ["HR", "IT", np.nan, "IT", "Finance"],
    "Salary": [45000, np.nan, 55000, 80000, np.nan],
    "Experience": [2, 5, 3, np.nan, 4]
})

employees

  Employee Department   Salary  Experience
0     Amit         HR  45000.0         2.0
1     Neha         IT      NaN         5.0
2    Rahul        NaN  55000.0         3.0
3    Priya         IT  80000.0         NaN
4    Karan    Finance      NaN         4.0

In [7]:
print(employees.notna())

   Employee  Department  Salary  Experience
0      True        True    True        True
1      True        True   False        True
2      True       False    True        True
3      True        True    True       False
4      True        True   False        True

In [9]:
employees["Salary"].notna()

0     True
1    False
2     True
3     True
4    False
Name: Salary, dtype: bool

In [10]:
employees[employees["Salary"].notna()]

  Employee Department   Salary  Experience
0     Amit         HR  45000.0         2.0
2    Rahul        NaN  55000.0         3.0
3    Priya         IT  80000.0         NaN

In [12]:
employees.notna().sum()

Employee      5
Department    4
Salary        3
Experience    4
dtype: int64

## dropna()

**Definition:**
Removes rows or columns containing missing values (`NaN`).

**Syntax:**
dataframe.dropna()

dataframe.dropna(axis=1)

In [13]:
import pandas as pd
import numpy as np
employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan"],
    "Department": ["HR", "IT", np.nan, "IT", "Finance"],
    "Salary": [45000, np.nan, 55000, 80000, np.nan],
    "Experience": [2, 5, 3, np.nan, 4]
})
employees

  Employee Department   Salary  Experience
0     Amit         HR  45000.0         2.0
1     Neha         IT      NaN         5.0
2    Rahul        NaN  55000.0         3.0
3    Priya         IT  80000.0         NaN
4    Karan    Finance      NaN         4.0

In [14]:
employees.dropna()

  Employee Department   Salary  Experience
0     Amit         HR  45000.0         2.0

In [39]:
employees.dropna(axis=0)  #Remove all columns that contain at least one NaN.

  Employee Department   Salary  Experience
0     Amit         HR  45000.0         2.0

In [24]:
employees.dropna(axis=1)

  Employee
0     Amit
1     Neha
2    Rahul
3    Priya
4    Karan

In [28]:
employees.dropna(axis=0)  #Remove all rows that contain at least one NaN.

  Employee Department   Salary  Experience
0     Amit         HR  45000.0         2.0

In [27]:
employees.dropna(how="all")  #Removes a row only when every value is NaN.

  Employee Department   Salary  Experience
0     Amit         HR  45000.0         2.0
1     Neha         IT      NaN         5.0
2    Rahul        NaN  55000.0         3.0
3    Priya         IT  80000.0         NaN
4    Karan    Finance      NaN         4.0

In [29]:
employees.dropna(subset=["Salary"])

  Employee Department   Salary  Experience
0     Amit         HR  45000.0         2.0
2    Rahul        NaN  55000.0         3.0
3    Priya         IT  80000.0         NaN

## fillna()

**Definition:**
Replaces missing values (`NaN`) with a specified value or method.

**Syntax:**
dataframe.fillna(value)

dataframe.fillna(value={"column": value})

dataframe.fillna(method="ffill")

dataframe.fillna(method="bfill")

In [30]:
import pandas as pd
import numpy as np

employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan"],
    "Department": ["HR", "IT", np.nan, "IT", "Finance"],
    "Salary": [45000, np.nan, 55000, 80000, np.nan],
    "Experience": [2, 5, 3, np.nan, 4]
})

employees

  Employee Department   Salary  Experience
0     Amit         HR  45000.0         2.0
1     Neha         IT      NaN         5.0
2    Rahul        NaN  55000.0         3.0
3    Priya         IT  80000.0         NaN
4    Karan    Finance      NaN         4.0

In [31]:
#Fill All Missing Values with a Single Value
employees.fillna(0)

  Employee Department   Salary  Experience
0     Amit         HR  45000.0         2.0
1     Neha         IT      0.0         5.0
2    Rahul          0  55000.0         3.0
3    Priya         IT  80000.0         0.0
4    Karan    Finance      0.0         4.0

In [34]:
employees["Salary"].fillna(60000)   #Fill Only One Column

0    45000.0
1    60000.0
2    55000.0
3    80000.0
4    60000.0
Name: Salary, dtype: float64

In [40]:
employees.fillna({       #Fill Different Columns with Different Values
    "Department":"Unknown",
    "Salary":50000,
    "Experience":0
    
})

  Employee Department   Salary  Experience
0     Amit         HR  45000.0         2.0
1     Neha         IT  50000.0         5.0
2    Rahul    Unknown  55000.0         3.0
3    Priya         IT  80000.0         0.0
4    Karan    Finance  50000.0         4.0

In [36]:
#Forward Fill (ffill)
employees.ffill()

  Employee Department   Salary  Experience
0     Amit         HR  45000.0         2.0
1     Neha         IT  45000.0         5.0
2    Rahul         IT  55000.0         3.0
3    Priya         IT  80000.0         3.0
4    Karan    Finance  80000.0         4.0

In [37]:
#Backward Fill (bfill)
employees.bfill()

  Employee Department   Salary  Experience
0     Amit         HR  45000.0         2.0
1     Neha         IT  55000.0         5.0
2    Rahul         IT  55000.0         3.0
3    Priya         IT  80000.0         4.0
4    Karan    Finance      NaN         4.0

## replace()

**Definition:**
Replaces one or more specified values in a DataFrame or Series with new values.

**Syntax:**
dataframe.replace(old_value, new_value)

dataframe.replace({old1: new1, old2: new2})

In [1]:
import pandas as pd

employees = pd.DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya", "Karan"],
    "Department": ["HR", "IT", "NA", "IT", "Finance"],
    "Salary": [45000, 0, 55000, 80000, 0],
    "Experience": [2, 5, 3, 7, 4]
})

employees

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
1     Neha         IT       0           5
2    Rahul         NA   55000           3
3    Priya         IT   80000           7
4    Karan    Finance       0           4

In [3]:
#Replace a single Value 
employees.replace(0,50000)

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
1     Neha         IT   50000           5
2    Rahul         NA   55000           3
3    Priya         IT   80000           7
4    Karan    Finance   50000           4

In [6]:
import numpy as np
import pandas as pd
employees.replace("NA","Unknown")

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
1     Neha         IT       0           5
2    Rahul    Unknown   55000           3
3    Priya         IT   80000           7
4    Karan    Finance       0           4

In [7]:
employees.replace({
    "NA":"Unknown",
    0:5000
})

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
1     Neha         IT    5000           5
2    Rahul    Unknown   55000           3
3    Priya         IT   80000           7
4    Karan    Finance    5000           4

In [8]:
employees["Salary"].replace(0,50000)

0    45000
1    50000
2    55000
3    80000
4    50000
Name: Salary, dtype: int64