In [1]:
import pandas as pd
employees = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Neha", "Rahul", "Sneha", "Karan", "Priya"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Finance"],
    "Age": [25, 30, 28, 35, 26, 32],
    "Salary": [45000, 70000, 65000, 85000, 48000, 72000]
})
employees

   Emp_ID   Name Department  Age  Salary
0     101   Amit         HR   25   45000
1     102   Neha         IT   30   70000
2     103  Rahul    Finance   28   65000
3     104  Sneha         IT   35   85000
4     105  Karan         HR   26   48000
5     106  Priya    Finance   32   72000

# Definition: sort_values()

`sort_values()` is a Pandas method used to arrange the rows of a DataFrame based on the values of one or more columns in either ascending or descending order.

In [2]:
employees.sort_values(by="Salary")

   Emp_ID   Name Department  Age  Salary
0     101   Amit         HR   25   45000
4     105  Karan         HR   26   48000
2     103  Rahul    Finance   28   65000
1     102   Neha         IT   30   70000
5     106  Priya    Finance   32   72000
3     104  Sneha         IT   35   85000

In [3]:
employees.sort_values(by="Salary",ascending=False)

   Emp_ID   Name Department  Age  Salary
3     104  Sneha         IT   35   85000
5     106  Priya    Finance   32   72000
1     102   Neha         IT   30   70000
2     103  Rahul    Finance   28   65000
4     105  Karan         HR   26   48000
0     101   Amit         HR   25   45000

In [4]:
employees.sort_values(
    by=["Department", "Salary"],
    ascending=[True, False]
)

   Emp_ID   Name Department  Age  Salary
5     106  Priya    Finance   32   72000
2     103  Rahul    Finance   28   65000
4     105  Karan         HR   26   48000
0     101   Amit         HR   25   45000
3     104  Sneha         IT   35   85000
1     102   Neha         IT   30   70000

In [5]:
employees.sort_values(by="Salary",ascending=False,ignore_index=True)

   Emp_ID   Name Department  Age  Salary
0     104  Sneha         IT   35   85000
1     106  Priya    Finance   32   72000
2     102   Neha         IT   30   70000
3     103  Rahul    Finance   28   65000
4     105  Karan         HR   26   48000
5     101   Amit         HR   25   45000

In [6]:
employee_salary = pd.DataFrame({
    "Name": ["Amit", "Neha", "Rahul", "Sneha"],
    "Salary": [45000, None, 65000, 85000]
})

employee_salary

    Name   Salary
0   Amit  45000.0
1   Neha      NaN
2  Rahul  65000.0
3  Sneha  85000.0

In [7]:
employee_salary.sort_values(by="Salary",na_position="first")

    Name   Salary
1   Neha      NaN
0   Amit  45000.0
2  Rahul  65000.0
3  Sneha  85000.0

# Definition: sort_index()

`sort_index()` is a Pandas method used to arrange a DataFrame based on its row index or column index instead of the values stored inside the DataFrame.

In [8]:
employees = pd.DataFrame({
    "Name": ["Amit", "Neha", "Rahul", "Sneha"],
    "Salary": [45000, 70000, 65000, 85000]
},
index=[104, 101, 103, 102])

employees

      Name  Salary
104   Amit   45000
101   Neha   70000
103  Rahul   65000
102  Sneha   85000

In [10]:
employees.sort_index()

      Name  Salary
101   Neha   70000
102  Sneha   85000
103  Rahul   65000
104   Amit   45000

In [12]:
employees.sort_index(ascending=False)

      Name  Salary
104   Amit   45000
103  Rahul   65000
102  Sneha   85000
101   Neha   70000

In [13]:
employee_data = pd.DataFrame({
    "Salary": [45000, 70000],
    "Age": [25, 30],
    "Department": ["HR", "IT"],
    "Name": ["Amit", "Neha"]
})
employee_data

   Salary  Age Department  Name
0   45000   25         HR  Amit
1   70000   30         IT  Neha

In [16]:
employee_data.sort_index(axis=1)

   Age Department  Name  Salary
0   25         HR  Amit   45000
1   30         IT  Neha   70000

# Definition: rank()

`rank()` is a Pandas method used to assign a rank (position) to each value in a Series or DataFrame based on its magnitude.

In [17]:
import pandas as pd
employees = pd.DataFrame({
    "Name": ["Amit", "Neha", "Rahul", "Sneha", "Karan"],
    "Salary": [45000, 70000, 65000, 85000, 48000]
})
employees

    Name  Salary
0   Amit   45000
1   Neha   70000
2  Rahul   65000
3  Sneha   85000
4  Karan   48000

In [19]:
employees["Salary"].rank(ascending=False)

0    5.0
1    2.0
2    3.0
3    1.0
4    4.0
Name: Salary, dtype: float64

In [21]:
employees["Rank"]=employees["Salary"].rank(ascending=False)
employees

    Name  Salary  Rank
0   Amit   45000   5.0
1   Neha   70000   2.0
2  Rahul   65000   3.0
3  Sneha   85000   1.0
4  Karan   48000   4.0

In [22]:
employees = pd.DataFrame({
    "Name": ["Amit", "Neha", "Rahul", "Sneha"],
    "Salary": [70000, 70000, 50000, 90000]
})
employees

    Name  Salary
0   Amit   70000
1   Neha   70000
2  Rahul   50000
3  Sneha   90000

In [23]:
employees["Salary"].rank(ascending=False)

0    2.5
1    2.5
2    4.0
3    1.0
Name: Salary, dtype: float64

# Different Ranking Methods

In [24]:
employees["Salary"].rank(
    ascending=False,
    method="average"     # Default method
)

0    2.5
1    2.5
2    4.0
3    1.0
Name: Salary, dtype: float64

In [27]:
employees["Salary"].rank(
    ascending=False,
    method="min"   # All tied values receive the smallest possible rank
)

0    2.0
1    2.0
2    4.0
3    1.0
Name: Salary, dtype: float64

In [28]:
employees["Salary"].rank(
    ascending=False,
    method="max"    # All tied values receive the largest possible rank.
)

0    3.0
1    3.0
2    4.0
3    1.0
Name: Salary, dtype: float64

In [29]:
employees["Salary"].rank(
    ascending=False,
    method="first"  #if values are equal,rank them according to their order of appearance.
)

0    2.0
1    3.0
2    4.0
3    1.0
Name: Salary, dtype: float64

In [30]:
employees["Salary"].rank(
    ascending=False,
    method="dense"
)

0    2.0
1    2.0
2    3.0
3    1.0
Name: Salary, dtype: float64