In [1]:
import pandas as pd
employees = pd.DataFrame({
    "Emp_ID": [101,102,103,104,105,106,107,108],
    "Name": ["Amit","Neha","Rahul","Sneha","Karan","Priya","Vikas","Anjali"],
    "Department": ["HR","IT","Finance","IT","HR","Finance","IT","HR"],
    "Gender": ["Male","Female","Male","Female","Male","Female","Male","Female"],
    "Experience": [2,5,4,8,3,6,2,7],
    "Salary": [45000,70000,65000,85000,48000,72000,60000,55000]
})
employees

   Emp_ID    Name Department  Gender  Experience  Salary
0     101    Amit         HR    Male           2   45000
1     102    Neha         IT  Female           5   70000
2     103   Rahul    Finance    Male           4   65000
3     104   Sneha         IT  Female           8   85000
4     105   Karan         HR    Male           3   48000
5     106   Priya    Finance  Female           6   72000
6     107   Vikas         IT    Male           2   60000
7     108  Anjali         HR  Female           7   55000

# Definition: groupby()

`groupby()` is a Pandas method used to divide data into groups based on one or more columns so that calculations can be performed separately on each group.

In [2]:
# Syntax: df.groupby("column_name")
#         df.groupby(["column1", "column2"])

In [3]:
employees.groupby("Department")

# Aggregation using mean()

Aggregation means combining multiple values into a single summarized value.

In [4]:
# Avg Salary of each Department
employees.groupby("Department")["Salary"].mean()

Department
Finance    68500.000000
HR         49333.333333
IT         71666.666667
Name: Salary, dtype: float64

In [5]:
#Avg Experience of each Department
employees.groupby("Department")["Experience"].mean()

Department
Finance    5.0
HR         4.0
IT         5.0
Name: Experience, dtype: float64

In [7]:
employees.groupby("Department")[["Salary","Experience"]].mean()

                  Salary  Experience
Department
Finance     68500.000000         5.0
HR          49333.333333         4.0
IT          71666.666667         5.0

# Aggregation Functions with groupby()

Aggregation functions summarize the data in each group into a single value such as sum, average, count, minimum, or maximum.

In [9]:
# Sum
employees.groupby("Department")["Salary"].mean()

Department
Finance    68500.000000
HR         49333.333333
IT         71666.666667
Name: Salary, dtype: float64

In [13]:
# Count
employees.groupby("Department")["Salary"].count()
# count() ignores missing values.

Department
Finance    2
HR         3
IT         3
Name: Salary, dtype: int64

In [14]:
# Size  :-  Find the total number of rows in each department.
employees.groupby("Department").size()
# size() counts all rows.

Department
Finance    2
HR         3
IT         3
dtype: int64

In [15]:
# min()
employees.groupby("Department")["Salary"].min()

Department
Finance    65000
HR         45000
IT         60000
Name: Salary, dtype: int64

In [17]:
# Max()
employees.groupby("Department")["Salary"].max()

Department
Finance    72000
HR         55000
IT         85000
Name: Salary, dtype: int64

In [18]:
# Median
employees.groupby("Department")["Salary"].median()

Department
Finance    68500.0
HR         48000.0
IT         70000.0
Name: Salary, dtype: float64

In [21]:
# std()  #To calculate standard Deviation
employees.groupby("Department")["Salary"].std()

Department
Finance     4949.747468
HR          5131.601439
IT         12583.057392
Name: Salary, dtype: float64

In [22]:
# Var  #To calculate variance
employees.groupby("Department")["Salary"].var()

Department
Finance    2.450000e+07
HR         2.633333e+07
IT         1.583333e+08
Name: Salary, dtype: float64

In [24]:
# First To show first value of every group
employees.groupby("Department").first()

            Emp_ID   Name  Gender  Experience  Salary
Department
Finance        103  Rahul    Male           4   65000
HR             101   Amit    Male           2   45000
IT             102   Neha  Female           5   70000

In [25]:
# last()    To show last value of every group
employees.groupby("Department").last()

            Emp_ID    Name  Gender  Experience  Salary
Department
Finance        106   Priya  Female           6   72000
HR             108  Anjali  Female           7   55000
IT             107   Vikas    Male           2   60000

In [28]:
#  nunique()    Count unique values.
employees.groupby("Department")["Gender"].nunique()

Department
Finance    2
HR         2
IT         2
Name: Gender, dtype: int64

# Multiple Aggregations using agg()

`agg()` (aggregate) allows us to perform one or more aggregation functions on grouped data in a single operation.

In [29]:
#  df.groupby("column").agg(functions)
             
            #or

# df.groupby("column").agg({
#   "column1": [...],
#  "column2": [...]
#  })

In [30]:
employees.groupby("Department")["Salary"].agg(
    ["mean", "max", "min"]
)

                    mean    max    min
Department
Finance     68500.000000  72000  65000
HR          49333.333333  55000  45000
IT          71666.666667  85000  60000

In [31]:
employees.groupby("Department")["Salary"].agg(
    ["count", "sum", "mean", "median", "min", "max"]
)

            count     sum          mean   median    min    max
Department
Finance         2  137000  68500.000000  68500.0  65000  72000
HR              3  148000  49333.333333  48000.0  45000  55000
IT              3  215000  71666.666667  70000.0  60000  85000

In [32]:
employees.groupby("Department").agg({
    "Salary": ["mean", "max"],
    "Experience": "mean"
})

                  Salary        Experience
                    mean    max       mean
Department
Finance     68500.000000  72000        5.0
HR          49333.333333  55000        4.0
IT          71666.666667  85000        5.0

In [36]:
employees.groupby("Department").agg(
    Average_Salary=("Salary", "mean"),
    Highest_Salary=("Salary", "max"),
    Lowest_Salary=("Salary", "min"),
    Avg_Experience=("Experience", "mean")
)

            Average_Salary  Highest_Salary  Lowest_Salary  Avg_Experience
Department
Finance       68500.000000           72000          65000             5.0
HR            49333.333333           55000          45000             4.0
IT            71666.666667           85000          60000             5.0

In [37]:
employees.groupby("Department").agg(
    Total_Salary=("Salary", "sum"),
    Average_Salary=("Salary", "mean"),
    Highest_Salary=("Salary", "max"),
    Employees=("Emp_ID", "count")
)

            Total_Salary  Average_Salary  Highest_Salary  Employees
Department
Finance           137000    68500.000000           72000          2
HR                148000    49333.333333           55000          3
IT                215000    71666.666667           85000          3

# Grouping by Multiple Columns

Grouping by multiple columns allows us to divide the data into groups based on combinations of two or more columns, enabling more detailed analysis.

In [38]:
employees.groupby(["Department", "Gender"])

In [39]:
employees.groupby(["Department", "Gender"])["Salary"].mean()

Department  Gender
Finance     Female    72000.0
            Male      65000.0
HR          Female    55000.0
            Male      46500.0
IT          Female    77500.0
            Male      60000.0
Name: Salary, dtype: float64

In [40]:
employees.groupby(
    ["Department", "Gender"]
)["Salary"].agg(["mean", "max"])

                      mean    max
Department Gender
Finance    Female  72000.0  72000
           Male    65000.0  65000
HR         Female  55000.0  55000
           Male    46500.0  48000
IT         Female  77500.0  85000
           Male    60000.0  60000

In [41]:
employees.groupby(
    ["Department", "Gender"]
).agg(
    Average_Salary=("Salary", "mean"),
    Highest_Salary=("Salary", "max"),
    Employees=("Emp_ID", "count")
)

                   Average_Salary  Highest_Salary  Employees
Department Gender
Finance    Female         72000.0           72000          1
           Male           65000.0           65000          1
HR         Female         55000.0           55000          1
           Male           46500.0           48000          2
IT         Female         77500.0           85000          2
           Male           60000.0           60000          1

In [45]:
employees.groupby(
    ["Department", "Gender"]
).agg(
    Average_Salary=("Salary", "mean"),
    Highest_Salary=("Salary", "max"),
    Employees=("Emp_ID", "count")
).reset_index()

  Department  Gender  Average_Salary  Highest_Salary  Employees
0    Finance  Female         72000.0           72000          1
1    Finance    Male         65000.0           65000          1
2         HR  Female         55000.0           55000          1
3         HR    Male         46500.0           48000          2
4         IT  Female         77500.0           85000          2
5         IT    Male         60000.0           60000          1

In [44]:
employees.groupby(
    ["Department", "Gender"]
)["Salary"].mean().reset_index()  #reset_index() converts the index levels back into normal columns.

  Department  Gender   Salary
0    Finance  Female  72000.0
1    Finance    Male  65000.0
2         HR  Female  55000.0
3         HR    Male  46500.0
4         IT  Female  77500.0
5         IT    Male  60000.0