In [1]:
import pandas as pd
employees = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104],
    "Name": ["Amit", "Neha", "Rahul", "Sneha"],
    "Department": ["HR", "IT", "Finance", "IT"]
})
employees

   Emp_ID   Name Department
0     101   Amit         HR
1     102   Neha         IT
2     103  Rahul    Finance
3     104  Sneha         IT

In [2]:
salary = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104],
    "Salary": [45000, 70000, 65000, 85000]
})
salary

   Emp_ID  Salary
0     101   45000
1     102   70000
2     103   65000
3     104   85000

# Definition: merge()

`merge()` is a Pandas method used to combine two DataFrames based on one or more common columns (keys), similar to SQL joins.

pd.merge(

    left,

    right,
    
    on=None,
    
    how="inner"
)

In [4]:
pd.merge(
    employees,
    salary,
    on="Emp_ID"
)

   Emp_ID   Name Department  Salary
0     101   Amit         HR   45000
1     102   Neha         IT   70000
2     103  Rahul    Finance   65000
3     104  Sneha         IT   85000

# Inner Join

An Inner Join returns only the rows where the key exists in **both** DataFrames.

In [5]:
employees = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104, 105],
    "Name": ["Amit", "Neha", "Rahul", "Sneha", "Karan"],
    "Department": ["HR", "IT", "Finance", "IT", "HR"]
})
employees

   Emp_ID   Name Department
0     101   Amit         HR
1     102   Neha         IT
2     103  Rahul    Finance
3     104  Sneha         IT
4     105  Karan         HR

In [6]:
salary = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104, 106],
    "Salary": [45000, 70000, 65000, 85000, 50000]
})
salary

   Emp_ID  Salary
0     101   45000
1     102   70000
2     103   65000
3     104   85000
4     106   50000

In [7]:
pd.merge(
    employees,
    salary,
    on="Emp_ID",
    how="inner"
)

   Emp_ID   Name Department  Salary
0     101   Amit         HR   45000
1     102   Neha         IT   70000
2     103  Rahul    Finance   65000
3     104  Sneha         IT   85000

# Left Join

A Left Join returns **all rows from the left DataFrame** and only the matching rows from the right DataFrame. If no match is found, the missing values are filled with `NaN`.

In [8]:
pd.merge(
    employees,
    salary,
    on="Emp_ID",
    how="left"
)

   Emp_ID   Name Department   Salary
0     101   Amit         HR  45000.0
1     102   Neha         IT  70000.0
2     103  Rahul    Finance  65000.0
3     104  Sneha         IT  85000.0
4     105  Karan         HR      NaN

# Right Join

A Right Join returns **all rows from the right DataFrame** and only the matching rows from the left DataFrame. If no match is found, the missing values are filled with `NaN`.

In [9]:
pd.merge(
    employees,
    salary,
    on="Emp_ID",
    how="right"
)

   Emp_ID   Name Department  Salary
0     101   Amit         HR   45000
1     102   Neha         IT   70000
2     103  Rahul    Finance   65000
3     104  Sneha         IT   85000
4     106    NaN        NaN   50000

# Outer Join

An Outer Join returns **all rows from both DataFrames**. If a row has no matching key in the other DataFrame, the missing values are filled with `NaN`.

In [12]:
pd.merge(
    employees,
    salary,
    on="Emp_ID",
    how="outer"
)

   Emp_ID   Name Department   Salary
0     101   Amit         HR  45000.0
1     102   Neha         IT  70000.0
2     103  Rahul    Finance  65000.0
3     104  Sneha         IT  85000.0
4     105  Karan         HR      NaN
5     106    NaN        NaN  50000.0

# Merging on Different Column Names

`left_on` and `right_on` are used when the common key has different column names in the two DataFrames.

pd.merge(
   
    left_df,
    
    right_df,
    
    left_on="column_in_left",
    
    right_on="column_in_right"
)

In [13]:
salary = pd.DataFrame({
    "Employee_ID": [101,102,103,104],
    "Salary": [45000,70000,65000,85000]
})

In [16]:
pd.merge(
    employees,
    salary,
    left_on="Emp_ID",
    right_on="Employee_ID",
    how="outer"
)

   Emp_ID   Name Department  Employee_ID   Salary
0     101   Amit         HR        101.0  45000.0
1     102   Neha         IT        102.0  70000.0
2     103  Rahul    Finance        103.0  65000.0
3     104  Sneha         IT        104.0  85000.0
4     105  Karan         HR          NaN      NaN

In [17]:
# To drop one emp ID column 
result=pd.merge(
    employees,
    salary,
    left_on="Emp_ID",
    right_on="Employee_ID",
    how="outer"
)
result.drop(columns="Employee_ID")

   Emp_ID   Name Department   Salary
0     101   Amit         HR  45000.0
1     102   Neha         IT  70000.0
2     103  Rahul    Finance  65000.0
3     104  Sneha         IT  85000.0
4     105  Karan         HR      NaN

# join()

`join()` is a Pandas method used to combine DataFrames primarily based on their indexes. It is a convenient alternative to `merge()` when the index is the matching key.

left_df.join(right_df)

In [18]:
employees = pd.DataFrame({
    "Name": ["Amit", "Neha", "Rahul", "Sneha"],
    "Department": ["HR", "IT", "Finance", "IT"]
},
index=[101,102,103,104])
employees

      Name Department
101   Amit         HR
102   Neha         IT
103  Rahul    Finance
104  Sneha         IT

In [19]:
salary = pd.DataFrame({
    "Salary":[45000,70000,65000,85000]
},
index=[101,102,103,104])
salary

     Salary
101   45000
102   70000
103   65000
104   85000

In [20]:
employees.join(salary)

      Name Department  Salary
101   Amit         HR   45000
102   Neha         IT   70000
103  Rahul    Finance   65000
104  Sneha         IT   85000

In [21]:
employees.join(salary,how="inner")

      Name Department  Salary
101   Amit         HR   45000
102   Neha         IT   70000
103  Rahul    Finance   65000
104  Sneha         IT   85000

In [22]:
employees.join(
    salary,
    how="outer"
)

      Name Department  Salary
101   Amit         HR   45000
102   Neha         IT   70000
103  Rahul    Finance   65000
104  Sneha         IT   85000

# concat()

`concat()` is a Pandas function used to combine two or more DataFrames by stacking them either vertically (row-wise) or horizontally (column-wise).

pd.concat(
    [df1, df2]
)

In [23]:
df1 = pd.DataFrame({
    "Emp_ID":[101,102],
    "Name":["Amit","Neha"]
})
df1

   Emp_ID  Name
0     101  Amit
1     102  Neha

In [24]:
df2 = pd.DataFrame({
    "Emp_ID":[103,104],
    "Name":["Rahul","Sneha"]
})
df2

   Emp_ID   Name
0     103  Rahul
1     104  Sneha

In [25]:
pd.concat([df1,df2])

   Emp_ID   Name
0     101   Amit
1     102   Neha
0     103  Rahul
1     104  Sneha

In [26]:
pd.concat(
    [df1,df2],
    ignore_index="true"
)

   Emp_ID   Name
0     101   Amit
1     102   Neha
2     103  Rahul
3     104  Sneha

In [27]:
pd.concat(
    [df1,df2],
    axis=1
)

   Emp_ID  Name  Emp_ID   Name
0     101  Amit     103  Rahul
1     102  Neha     104  Sneha

# Merge vs Join vs Concat

| Feature | `merge()` | `join()` | `concat()` |
|---------|-----------|----------|------------|
| **Purpose** | Combine DataFrames using common columns | Combine DataFrames using indexes | Stack DataFrames vertically or horizontally |
| **Matching Key** | Columns (default) | Index (default) | No matching key required |
| **Default Join Type** | `inner` | `left` | Vertical (`axis=0`) |
| **Can Join on Different Column Names?** | ✅ Yes (`left_on`, `right_on`) | ⚠️ Limited | ❌ Not Applicable |
| **Supports Inner Join** | ✅ Yes | ✅ Yes | ❌ No |
| **Supports Left Join** | ✅ Yes | ✅ Yes | ❌ No |
| **Supports Right Join** | ✅ Yes | ✅ Yes | ❌ No |
| **Supports Outer Join** | ✅ Yes | ✅ Yes | ❌ No |
| **Requires Common Key?** | ✅ Yes | ✅ Yes (usually index) | ❌ No |
| **Works Mainly With** | Columns | Indexes | Rows or Columns |
| **Default Axis** | Not Applicable | Not Applicable | `axis=0` |
| **Can Stack Columns?** | ❌ No | ❌ No | ✅ Yes (`axis=1`) |
| **Most Common Use** | SQL-style joins | Index-based joins | Combining multiple DataFrames/files |


---

# Join Types in `merge()`

| Join Type | Keeps | Missing Values (`NaN`) |
|-----------|-------|------------------------|
| **Inner Join** | Only matching rows | ❌ No |
| **Left Join** | All rows from the left DataFrame | ✅ Yes (if no match in right) |
| **Right Join** | All rows from the right DataFrame | ✅ Yes (if no match in left) |
| **Outer Join** | All rows from both DataFrames | ✅ Yes (wherever no match exists) |

---

# `merge()` vs `join()`

| `merge()` | `join()` |
|------------|----------|
| Joins using columns by default | Joins using indexes by default |
| Default join is **Inner** | Default join is **Left** |
| More flexible | Simpler syntax |
| Supports `left_on` & `right_on` | Mainly index-based joins |
| Most commonly used | Used when indexes are meaningful |

---

# `merge()` vs `concat()`

| `merge()` | `concat()` |
|------------|------------|
| Matches rows using a common key | Simply stacks DataFrames |
| Requires a common column (or index) | No common key required |
| SQL-like joins | Appending/combining DataFrames |
| Used for relational data | Used for combining multiple datasets/files |

---

# `join()` vs `concat()`

| `join()` | `concat()` |
|-----------|------------|
| Matches indexes | Does not match keys |
| Combines related data | Simply stacks data |
| Supports join types | Supports row-wise and column-wise concatenation |

---

# Easy Memory Trick

| Function | Think Of |
|----------|----------|
| `merge()` | **Match → Combine** |
| `join()` | **Match Index → Combine** |
| `concat()` | **Stack → Done** |