# pivot()

`pivot()` is a Pandas method used to reshape a DataFrame by converting unique values from one column into new columns. It does **not** perform any aggregation.It does not woro with duplicate combinations.

df.pivot(

    index=None,
    
    columns=None,
    
    values=None
)

In [1]:
import pandas as pd
sales = pd.DataFrame({
    "Region": ["North", "North", "South", "South"],
    "Product": ["Laptop", "Phone", "Laptop", "Phone"],
    "Sales": [50000, 30000, 40000, 35000]
})
sales

  Region Product  Sales
0  North  Laptop  50000
1  North   Phone  30000
2  South  Laptop  40000
3  South   Phone  35000

In [2]:
sales.pivot(
    index="Region",
    columns="Product",
    values="Sales"
)

Product  Laptop  Phone
Region
North     50000  30000
South     40000  35000

# pivot_table()

`pivot_table()` is a Pandas method used to create Excel-like pivot tables by reshaping data and applying an aggregation function to duplicate values.

df.pivot_table(
    
    index=None,
    
    columns=None,
    
    values=None,
    
    aggfunc="mean"
)

In [3]:
sales = pd.DataFrame({
    "Region": ["North","North","North","South","South"],
    "Product": ["Laptop","Laptop","Phone","Laptop","Phone"],
    "Sales": [50000,55000,30000,40000,35000]
})
sales

  Region Product  Sales
0  North  Laptop  50000
1  North  Laptop  55000
2  North   Phone  30000
3  South  Laptop  40000
4  South   Phone  35000

In [4]:
sales.pivot_table(
    index="Region",
    columns="Product",
    values="Sales",
    aggfunc="sum"  # Default agg function is mean
)

Product  Laptop  Phone
Region
North    105000  30000
South     40000  35000

In [5]:
sales.pivot_table(
    index="Region",
    columns="Product",
    values="Sales",
    aggfunc="count" 
)

Product  Laptop  Phone
Region
North         2      1
South         1      1

In [6]:
sales.pivot_table(
    index="Region",
    columns="Product",
    values="Sales",
    aggfunc="max"
)

Product  Laptop  Phone
Region
North     55000  30000
South     40000  35000

In [7]:
sales.pivot_table(
    index="Region",
    columns="Product",
    values="Sales",
    aggfunc="min"
)

Product  Laptop  Phone
Region
North     50000  30000
South     40000  35000

In [8]:
sales.pivot_table(
    index="Region",
    columns="Product",
    values="Sales",
    aggfunc=["sum","mean","max","count"]
)

            sum            mean             max         count
Product  Laptop  Phone   Laptop    Phone Laptop  Phone Laptop Phone
Region
North    105000  30000  52500.0  30000.0  55000  30000      2     1
South     40000  35000  40000.0  35000.0  40000  35000      1     1

# Multiple Indexes in pivot_table()

`pivot_table()` allows you to use multiple columns as the row index, creating a hierarchical (MultiIndex) table for more detailed data analysis.

In [10]:
import pandas as pd

sales = pd.DataFrame({
    "Region": [
        "North", "North", "North",
        "South", "South", "South",
        "East", "East"
    ],
    "Salesperson": [
        "Amit", "Amit", "Neha",
        "Rahul", "Rahul", "Sneha",
        "Priya", "Priya"
    ],
    "Product": [
        "Laptop", "Phone", "Laptop",
        "Laptop", "Phone", "Laptop",
        "Laptop", "Phone"
    ],
    "Sales": [
        50000, 30000, 55000,
        40000, 35000, 45000,
        60000, 25000
    ]
})

sales

  Region Salesperson Product  Sales
0  North        Amit  Laptop  50000
1  North        Amit   Phone  30000
2  North        Neha  Laptop  55000
3  South       Rahul  Laptop  40000
4  South       Rahul   Phone  35000
5  South       Sneha  Laptop  45000
6   East       Priya  Laptop  60000
7   East       Priya   Phone  25000

In [12]:
sales.pivot_table(
    index=["Region","Salesperson"],
    columns="Product",
    values="Sales",
    aggfunc="sum"
)

Product              Laptop    Phone
Region Salesperson
East   Priya        60000.0  25000.0
North  Amit         50000.0  30000.0
       Neha         55000.0      NaN
South  Rahul        40000.0  35000.0
       Sneha        45000.0      NaN

In [13]:
sales.pivot_table(
    index="Region",
    columns=["Product", "Salesperson"],
    values="Sales",
    aggfunc="sum"
)

Product       Laptop                                        Phone           \
Salesperson     Amit     Neha    Priya    Rahul    Sneha     Amit    Priya
Region
East             NaN      NaN  60000.0      NaN      NaN      NaN  25000.0
North        50000.0  55000.0      NaN      NaN      NaN  30000.0      NaN
South            NaN      NaN      NaN  40000.0  45000.0      NaN      NaN

Product
Salesperson    Rahul
Region
East             NaN
North            NaN
South        35000.0

# fill_value

The `fill_value` parameter replaces missing values (`NaN`) in a pivot table with a specified value.

In [14]:
sales.pivot_table(
    index=["Region","Salesperson"],
    columns="Product",
    values="Sales",
    aggfunc="sum"
)

Product              Laptop    Phone
Region Salesperson
East   Priya        60000.0  25000.0
North  Amit         50000.0  30000.0
       Neha         55000.0      NaN
South  Rahul        40000.0  35000.0
       Sneha        45000.0      NaN

In [15]:
sales.pivot_table(
    index=["Region","Salesperson"],
    columns="Product",
    values="Sales",
    aggfunc="sum",
    fill_value=0
)

Product             Laptop  Phone
Region Salesperson
East   Priya         60000  25000
North  Amit          50000  30000
       Neha          55000      0
South  Rahul         40000  35000
       Sneha         45000      0

In [18]:
sales.pivot_table(
    index="Region",
    columns="Product",
    values="Sales",
    aggfunc="sum",
    fill_value="-"
)

Product  Laptop  Phone
Region
East      60000  25000
North    105000  30000
South     85000  35000

# margins=True

The `margins=True` parameter adds grand totals for rows and columns in a pivot table.

In [19]:
sales.pivot_table(
    index="Region",
    columns="Product",
    values="Sales",
    aggfunc="sum",
    margins=True
)

Product  Laptop  Phone     All
Region
East      60000  25000   85000
North    105000  30000  135000
South     85000  35000  120000
All      250000  90000  340000

In [23]:
sales.pivot_table(
    index="Region",
    columns="Product",
    values="Sales",
    aggfunc="sum",
    margins=True,
    margins_name="Grand Total"   #To rename the total column
    )

Product      Laptop  Phone  Grand Total
Region
East          60000  25000        85000
North        105000  30000       135000
South         85000  35000       120000
Grand Total  250000  90000       340000

In [24]:
sales.pivot_table(
    index=["Region","Salesperson"],
    columns="Product",
    values="Sales",
    aggfunc="sum",
    margins=True
)

Product               Laptop    Phone     All
Region Salesperson
East   Priya         60000.0  25000.0   85000
North  Amit          50000.0  30000.0   80000
       Neha          55000.0      NaN   55000
South  Rahul         40000.0  35000.0   75000
       Sneha         45000.0      NaN   45000
All                 250000.0  90000.0  340000

# crosstab()

`crosstab()` is a Pandas function used to create a frequency table that shows how often combinations of categorical variables occur.

pd.crosstab(
    index,
    columns
)

In [25]:
employees = pd.DataFrame({
    "Department": [
        "HR", "HR", "IT", "IT",
        "Finance", "Finance", "IT", "HR"
    ],
    "Gender": [
        "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female"
    ]
})

employees

  Department  Gender
0         HR    Male
1         HR  Female
2         IT    Male
3         IT  Female
4    Finance    Male
5    Finance  Female
6         IT    Male
7         HR  Female

In [30]:
pd.crosstab(employees["Department"],employees["Gender"])

Gender      Female  Male
Department
Finance          1     1
HR               2     1
IT               1     2

In [33]:
pd.crosstab(employees["Department"],
            employees["Gender"],
           margins="True",
           )

Gender      Female  Male  All
Department
Finance          1     1    2
HR               2     1    3
IT               1     2    3
All              4     4    8

In [35]:
pd.crosstab(employees["Department"],
            employees["Gender"],
            normalize="index"
)

Gender        Female      Male
Department
Finance     0.500000  0.500000
HR          0.666667  0.333333
IT          0.333333  0.666667

In [36]:
pd.crosstab(
    employees["Department"],
    employees["Gender"],
    normalize="columns"
)

Gender      Female  Male
Department
Finance       0.25  0.25
HR            0.50  0.25
IT            0.25  0.50

In [37]:
pd.crosstab(
    employees["Department"],
    employees["Gender"],
    normalize=True
)

Gender      Female   Male
Department
Finance      0.125  0.125
HR           0.250  0.125
IT           0.125  0.250