# Datetime

Datetime is a special Pandas data type used to store and work with dates and times. Converting date columns to datetime allows you to filter, sort, calculate differences, and extract date components efficiently.

In [2]:
import pandas as pd
df = pd.DataFrame({
    "Order_ID": [101, 102, 103, 104],
    "Order_Date": [
        "2025-01-15",
        "2025-02-10",
        "2025-03-05",
        "2025-04-20"
    ],
    "Sales": [1200, 2500, 1800, 3000]
})
df

   Order_ID  Order_Date  Sales
0       101  2025-01-15   1200
1       102  2025-02-10   2500
2       103  2025-03-05   1800
3       104  2025-04-20   3000

In [3]:
df.dtypes

Order_ID       int64
Order_Date    object
Sales          int64
dtype: object

In [5]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])  #Convert to Datetime

In [7]:
df.dtypes

Order_ID               int64
Order_Date    datetime64[ns]
Sales                  int64
dtype: object

# Date Extraction

The `.dt` accessor is used to extract different components from a datetime column, such as the year, month, day, weekday, and more.

In [9]:
import pandas as pd
df = pd.DataFrame({
    "Order_ID": [101, 102, 103, 104],
    "Order_Date": [
        "2025-01-15",
        "2025-02-10",
        "2025-03-05",
        "2025-04-20"
    ],
    "Sales": [1200, 2500, 1800, 3000]
})

df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df

   Order_ID Order_Date  Sales
0       101 2025-01-15   1200
1       102 2025-02-10   2500
2       103 2025-03-05   1800
3       104 2025-04-20   3000

In [11]:
df["Order_Date"].dt.year

0    2025
1    2025
2    2025
3    2025
Name: Order_Date, dtype: int32

In [18]:
df["Year"] = df["Order_Date"].dt.year
df

   Order_ID Order_Date  Sales  Month  Year
0       101 2025-01-15   1200      1  2025
1       102 2025-02-10   2500      2  2025
2       103 2025-03-05   1800      3  2025
3       104 2025-04-20   3000      4  2025

In [12]:
df["Order_Date"].dt.month

0    1
1    2
2    3
3    4
Name: Order_Date, dtype: int32

In [16]:
df["Month"] = df["Order_Date"].dt.month

In [17]:
df["Order_Date"].dt.day

0    15
1    10
2     5
3    20
Name: Order_Date, dtype: int32

In [19]:
df["Day"] = df["Order_Date"].dt.day

In [20]:
df["Order_Date"].dt.day_name()

0    Wednesday
1       Monday
2    Wednesday
3       Sunday
Name: Order_Date, dtype: object

In [21]:
df["Weekday"] = df["Order_Date"].dt.day_name()

In [23]:
df["Month_Name"] = df["Order_Date"].dt.month_name()

In [24]:
df

   Order_ID Order_Date  Sales  Month  Year  Day    Weekday Month_Name
0       101 2025-01-15   1200      1  2025   15  Wednesday    January
1       102 2025-02-10   2500      2  2025   10     Monday   February
2       103 2025-03-05   1800      3  2025    5  Wednesday      March
3       104 2025-04-20   3000      4  2025   20     Sunday      April

# Date Filtering

Date filtering is used to select rows based on specific dates or date ranges. It helps answer business questions such as finding recent orders, monthly sales, or transactions within a given period.

In [1]:
import pandas as pd
df = pd.DataFrame({
    "Order_ID": [101,102,103,104,105,106],
    "Order_Date":[
        "2025-01-15",
        "2025-02-10",
        "2025-03-05",
        "2025-04-20",
        "2025-05-12",
        "2025-06-18"
    ],
    "Sales":[1200,2500,1800,3000,2700,1500]
})
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df

   Order_ID Order_Date  Sales
0       101 2025-01-15   1200
1       102 2025-02-10   2500
2       103 2025-03-05   1800
3       104 2025-04-20   3000
4       105 2025-05-12   2700
5       106 2025-06-18   1500

In [2]:
df[df["Order_Date"] > "2025-03-01"]

   Order_ID Order_Date  Sales
2       103 2025-03-05   1800
3       104 2025-04-20   3000
4       105 2025-05-12   2700
5       106 2025-06-18   1500

In [3]:
df[df["Order_Date"] < "2025-03-01"]

   Order_ID Order_Date  Sales
0       101 2025-01-15   1200
1       102 2025-02-10   2500

In [4]:
df[df["Order_Date"] == "2025-04-20"]

   Order_ID Order_Date  Sales
3       104 2025-04-20   3000

In [5]:
df[
    (df["Order_Date"] >= "2025-02-01") &
    (df["Order_Date"] <= "2025-05-01")
]

   Order_ID Order_Date  Sales
1       102 2025-02-10   2500
2       103 2025-03-05   1800
3       104 2025-04-20   3000

In [6]:
df[df["Order_Date"].dt.month == 3]

   Order_ID Order_Date  Sales
2       103 2025-03-05   1800

In [7]:
df[df["Order_Date"].dt.year == 2025]

   Order_ID Order_Date  Sales
0       101 2025-01-15   1200
1       102 2025-02-10   2500
2       103 2025-03-05   1800
3       104 2025-04-20   3000
4       105 2025-05-12   2700
5       106 2025-06-18   1500

In [8]:
df[df["Order_Date"].dt.day_name() == "Monday"]

   Order_ID Order_Date  Sales
1       102 2025-02-10   2500
4       105 2025-05-12   2700

# Time Calculations

Time calculations are used to add, subtract, and compare dates. They help calculate durations such as delivery time, employee experience, payment due dates, and days between events.

In [9]:
import pandas as pd
df = pd.DataFrame({
    "Order_ID": [101, 102, 103, 104],
    "Order_Date": [
        "2025-01-15",
        "2025-02-10",
        "2025-03-05",
        "2025-04-20"
    ],
    "Delivery_Date": [
        "2025-01-18",
        "2025-02-15",
        "2025-03-09",
        "2025-04-25"
    ]
})
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Delivery_Date"] = pd.to_datetime(df["Delivery_Date"])
df

   Order_ID Order_Date Delivery_Date
0       101 2025-01-15    2025-01-18
1       102 2025-02-10    2025-02-15
2       103 2025-03-05    2025-03-09
3       104 2025-04-20    2025-04-25

In [10]:
df["Delivery_Date"] - df["Order_Date"]

0   3 days
1   5 days
2   4 days
3   5 days
dtype: timedelta64[ns]

In [11]:
df["Delivery_Time"] = df["Delivery_Date"] - df["Order_Date"]
df

   Order_ID Order_Date Delivery_Date Delivery_Time
0       101 2025-01-15    2025-01-18        3 days
1       102 2025-02-10    2025-02-15        5 days
2       103 2025-03-05    2025-03-09        4 days
3       104 2025-04-20    2025-04-25        5 days

In [13]:
df["Due_Date"] = df["Order_Date"] + pd.Timedelta(days=7)
df     #Add Days to a Date

   Order_ID Order_Date Delivery_Date Delivery_Time   Due_Date
0       101 2025-01-15    2025-01-18        3 days 2025-01-22
1       102 2025-02-10    2025-02-15        5 days 2025-02-17
2       103 2025-03-05    2025-03-09        4 days 2025-03-12
3       104 2025-04-20    2025-04-25        5 days 2025-04-27

In [16]:
df["Reminder_Date"] = df["Order_Date"] - pd.Timedelta(days=2)
df   #Subtract Days from a date

   Order_ID Order_Date Delivery_Date Delivery_Time   Due_Date Reminder_Date
0       101 2025-01-15    2025-01-18        3 days 2025-01-22    2025-01-13
1       102 2025-02-10    2025-02-15        5 days 2025-02-17    2025-02-08
2       103 2025-03-05    2025-03-09        4 days 2025-03-12    2025-03-03
3       104 2025-04-20    2025-04-25        5 days 2025-04-27    2025-04-18

# Real-World Date Analysis

Real-world date analysis involves using datetime operations to answer business questions such as monthly sales, delivery performance, weekday trends, and recent transactions.

In [17]:
import pandas as pd
df = pd.DataFrame({
    "Order_ID": [101,102,103,104,105,106],
    "Order_Date": [
        "2025-01-15",
        "2025-02-10",
        "2025-03-05",
        "2025-03-22",
        "2025-04-18",
        "2025-05-12"
    ],
    "Delivery_Date": [
        "2025-01-18",
        "2025-02-14",
        "2025-03-08",
        "2025-03-28",
        "2025-04-22",
        "2025-05-18"
    ],
    "Sales": [1200,2500,1800,3200,2700,4000]
})

df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Delivery_Date"] = pd.to_datetime(df["Delivery_Date"])
df

   Order_ID Order_Date Delivery_Date  Sales
0       101 2025-01-15    2025-01-18   1200
1       102 2025-02-10    2025-02-14   2500
2       103 2025-03-05    2025-03-08   1800
3       104 2025-03-22    2025-03-28   3200
4       105 2025-04-18    2025-04-22   2700
5       106 2025-05-12    2025-05-18   4000

In [21]:
#no of orders placed in each month?
df["Month"] = df["Order_Date"].dt.month_name()
df.groupby("Month")["Order_ID"].count()

Month
April       1
February    1
January     1
March       2
May         1
Name: Order_ID, dtype: int64

In [22]:
#no of orders placed in each month?
df.groupby("Month")["Sales"].sum()

Month
April       2700
February    2500
January     1200
March       5000
May         4000
Name: Sales, dtype: int64

In [23]:
# average delivery time
df["Delivery_Days"] = (
    df["Delivery_Date"] -
    df["Order_Date"]
).dt.days

In [24]:
df["Delivery_Days"].mean()

np.float64(4.333333333333333)

In [25]:
df[df["Delivery_Days"] > 5]

   Order_ID Order_Date Delivery_Date  Sales  Month  Delivery_Days
3       104 2025-03-22    2025-03-28   3200  March              6
5       106 2025-05-12    2025-05-18   4000    May              6

In [29]:
# Which weekday receives the most orders
df["Weekday"] = df["Order_Date"].dt.day_name()
df.groupby("Weekday")["Order_ID"].count()

Weekday
Friday       1
Monday       2
Saturday     1
Wednesday    2
Name: Order_ID, dtype: int64

In [30]:
# all orders after March 1, 2025
df[df["Order_Date"] > "2025-03-01"]

   Order_ID Order_Date Delivery_Date  Sales  Month  Delivery_Days    Weekday
2       103 2025-03-05    2025-03-08   1800  March              3  Wednesday
3       104 2025-03-22    2025-03-28   3200  March              6   Saturday
4       105 2025-04-18    2025-04-22   2700  April              4     Friday
5       106 2025-05-12    2025-05-18   4000    May              6     Monday

In [31]:
# Which month had the highest sales
df.groupby("Month")["Sales"].sum().sort_values(ascending=False)

Month
March       5000
May         4000
April       2700
February    2500
January     1200
Name: Sales, dtype: int64

In [32]:
df

,Order_ID,Order_Date,Delivery_Date,Sales,Month,Delivery_Days,Weekday
0,101,2025-01-15,2025-01-18,1200,January,3,Wednesday
1,102,2025-02-10,2025-02-14,2500,February,4,Monday
2,103,2025-03-05,2025-03-08,1800,March,3,Wednesday
3,104,2025-03-22,2025-03-28,3200,March,6,Saturday
4,105,2025-04-18,2025-04-22,2700,April,4,Friday
5,106,2025-05-12,2025-05-18,4000,May,6,Monday