# Apply Functions

Apply functions allow you to perform custom operations on Pandas data. They are useful when built-in methods are not enough and you need to apply your own logic to values, rows, or columns.

df["Column"].map(mapping)

In [1]:
import pandas as pd
df = pd.DataFrame({
    "Employee": ["John", "Alice", "Rohit", "Jane"],
    "Department": ["IT", "HR", "Finance", "IT"],
    "Salary": [50000, 60000, 45000, 70000]
})
df

  Employee Department  Salary
0     John         IT   50000
1    Alice         HR   60000
2    Rohit    Finance   45000
3     Jane         IT   70000

# map()

The `map()` method is used to transform or replace values in a single Pandas Series using a mapping (such as a dictionary, function, or another Series). It applies the specified mapping to each value individually and returns a new Series.

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["John", "Alice", "Rohit", "Jane"],
    "Department": ["IT", "HR", "Finance", "IT"],
    "Gender": ["M", "F", "M", "F"]
})

df

  Employee Department Gender
0     John         IT      M
1    Alice         HR      F
2    Rohit    Finance      M
3     Jane         IT      F

In [3]:
dept_map={
    "IT":"Information Technology",
    "HR":"Human Resources",
    "Finance":"Finance Department"
}
df["Department"]=df["Department"].map(dept_map)
df

  Employee              Department Gender
0     John  Information Technology      M
1    Alice         Human Resources      F
2    Rohit      Finance Department      M
3     Jane  Information Technology      F

In [4]:
gender_map = {
    "M": "Male",
    "F": "Female"
}
df["Gender"].map(gender_map)

0      Male
1    Female
2      Male
3    Female
Name: Gender, dtype: object

In [5]:
df["Employee"].map(len)  #map() applies the len() function to every value in the column.

0    4
1    5
2    5
3    4
Name: Employee, dtype: int64

In [6]:
df = pd.DataFrame({
    "Department": [
        "IT",
        "HR",
        "Finance",
        "Marketing"
    ]
})

In [7]:
dept_map = {
    "IT": "Information Technology",
    "HR": "Human Resources",
    "Finance": "Finance Department"
}

df["Department"].map(dept_map)

0    Information Technology
1           Human Resources
2        Finance Department
3                       NaN
Name: Department, dtype: object

In [8]:
df["Department"] = (
    df["Department"]
    .map(dept_map)
    .fillna("Other")
)

# apply()

The `apply()` method is used to apply a custom function to each value in a Series or to each row or column in a DataFrame. It is useful when built-in Pandas functions cannot perform the required operation.

df["Column"].apply(function)

In [9]:
import pandas as pd
df = pd.DataFrame({
    "Employee": ["John", "Alice", "Rohit", "Jane"],
    "Salary": [50000, 60000, 45000, 70000]
})
df

  Employee  Salary
0     John   50000
1    Alice   60000
2    Rohit   45000
3     Jane   70000

In [10]:
#Give every employee a 10% salary hike.
def increase_salary(salary):
    return salary * 1.10
df["Salary"].apply(increase_salary)

0    55000.0
1    66000.0
2    49500.0
3    77000.0
Name: Salary, dtype: float64

In [11]:
df["New_Salary"] = df["Salary"].apply(increase_salary)
df

  Employee  Salary  New_Salary
0     John   50000     55000.0
1    Alice   60000     66000.0
2    Rohit   45000     49500.0
3     Jane   70000     77000.0

In [12]:
#Create Salary Category

def salary_category(salary):
    if salary >= 60000:
        return "High"
    else:
        return "Normal"
df["Salary"].apply(salary_category)

0    Normal
1      High
2    Normal
3      High
Name: Salary, dtype: object

In [13]:
df["Category"] = df["Salary"].apply(salary_category)

df

  Employee  Salary  New_Salary Category
0     John   50000     55000.0   Normal
1    Alice   60000     66000.0     High
2    Rohit   45000     49500.0   Normal
3     Jane   70000     77000.0     High

In [14]:
df["Employee"].apply(len)

0    4
1    5
2    5
3    4
Name: Employee, dtype: int64

# apply() on DataFrame

The `apply()` method can be used on an entire DataFrame to apply a function to each row or each column. The `axis` parameter determines whether the function operates column-wise (`axis=0`) or row-wise (`axis=1`).

df.apply(function, axis=?)

In [15]:
import pandas as pd
df = pd.DataFrame({
    "Employee": ["John", "Alice", "Rohit", "Jane"],
    "Sales": [1200, 800, 1500, 900],
    "Target": [1000, 1000, 1200, 1000]
})
df

  Employee  Sales  Target
0     John   1200    1000
1    Alice    800    1000
2    Rohit   1500    1200
3     Jane    900    1000

In [16]:
df[["Sales", "Target"]].apply(max)

Sales     1500
Target    1200
dtype: int64

In [17]:
def check_target(row):
    if row["Sales"] >= row["Target"]:
        return "Achieved"
    else:
        return "Missed"
df["Status"] = df.apply(check_target, axis=1)
df

  Employee  Sales  Target    Status
0     John   1200    1000  Achieved
1    Alice    800    1000    Missed
2    Rohit   1500    1200  Achieved
3     Jane    900    1000    Missed

In [18]:
def total(row):
    return row["Sales"] + row["Target"]
df["Total"] = df.apply(total, axis=1)
df

  Employee  Sales  Target    Status  Total
0     John   1200    1000  Achieved   2200
1    Alice    800    1000    Missed   1800
2    Rohit   1500    1200  Achieved   2700
3     Jane    900    1000    Missed   1900

# lambda

A `lambda` function is a small anonymous (unnamed) function used to write simple operations in a single line. It is commonly used with methods like `apply()` and `map()` for quick transformations.

def function(x):

    return x * 2

↓

lambda x: x * 2

In [19]:
import pandas as pd
df = pd.DataFrame({
    "Employee": ["John", "Alice", "Rohit", "Jane"],
    "Salary": [50000, 60000, 45000, 70000]
})
df

  Employee  Salary
0     John   50000
1    Alice   60000
2    Rohit   45000
3     Jane   70000

In [20]:
df["Salary"].apply(lambda salary: salary * 1.10)

0    55000.0
1    66000.0
2    49500.0
3    77000.0
Name: Salary, dtype: float64

In [21]:
df["Salary"].apply(
    lambda salary: "High" if salary >= 60000 else "Normal"
)

0    Normal
1      High
2    Normal
3      High
Name: Salary, dtype: object

In [22]:
df["Employee"].apply(lambda name: len(name))

0    4
1    5
2    5
3    4
Name: Employee, dtype: int64

In [23]:
df["Employee"].map(lambda name: name.upper())

0     JOHN
1    ALICE
2    ROHIT
3     JANE
Name: Employee, dtype: object

In [27]:
df = pd.DataFrame({
    "Employee": ["John", "Alice", "Rohit", "Jane"],
    "Sales": [1200, 800, 1500, 900],
    "Target": [1000, 1000, 1200, 1000]
})

In [29]:
df["Status"] = df.apply(
    lambda row: "Achieved"
    if row["Sales"] >= row["Target"]
    else "Missed",
    axis=1
)
df

  Employee  Sales  Target    Status
0     John   1200    1000  Achieved
1    Alice    800    1000    Missed
2    Rohit   1500    1200  Achieved
3     Jane    900    1000    Missed

# When to Use map(), apply(), and lambda

`map()`, `apply()`, and `lambda` are used for transforming data in Pandas. Choosing the correct one depends on whether you're working with a single column or multiple columns, and whether the transformation is simple or requires custom logic.

# Notebook 14 Summary

| Topic | Purpose |
|--------|---------|
| `map()` | Replace or transform values in a single Series (column) using a dictionary, function, or another Series. |
| `apply()` (Series) | Apply a custom or built-in function to each value in a single column. |
| `apply()` (DataFrame) | Apply a function to each row (`axis=1`) or each column (`axis=0`) of a DataFrame. |
| `lambda` | Write short, anonymous one-line functions, commonly used with `map()` and `apply()`. |
| `axis=0` | Apply a function to each column of a DataFrame. |
| `axis=1` | Apply a function to each row of a DataFrame. |

---

# When to Use Each

| Situation | Use |
|-----------|-----|
| Replace values using a dictionary | `map()` |
| Apply a function to one column | `apply()` |
| Compare multiple columns | `apply(axis=1)` |
| Perform operations on each column | `apply(axis=0)` |
| Write a short one-line function | `lambda` |
| Write complex or reusable logic | `def` + `apply()` |

---

# Quick Comparison

| Feature | `map()` | `apply()` | `lambda` |
|---------|---------|-----------|----------|
| Works on Series | ✅ | ✅ | Used with `map()`/`apply()` |
| Works on DataFrame | ❌ | ✅ | ✅ (inside `apply`) |
| Dictionary Mapping | ✅ | ❌ | ❌ |
| Custom Functions | ✅ | ✅ | ✅ |
| Multiple Columns | ❌ | ✅ (`axis=1`) | ✅ (`axis=1`) |
| One-Line Logic | ❌ | ✅ | ✅ Best Choice |
| Complex Logic | ❌ | ✅ | ❌ |

---

# Easy Memory Trick

```text
Replace values?

↓

map()

-----------------------

One column + custom logic?

↓

apply()

-----------------------

Multiple columns?

↓

apply(axis=1)

-----------------------

One-line function?

↓

lambda

-----------------------

Complex or reusable logic?

↓

def + apply()
```