# Advanced Data Cleaning

Advanced Data Cleaning is the process of identifying and correcting issues in a dataset such as duplicate records, missing or incorrect values, inconsistent naming, and outliers to improve data quality before analysis.

# Duplicates

Duplicates are rows in a dataset that contain identical or repeated information. Identifying and removing duplicate records helps improve data quality and prevents incorrect analysis.

In [1]:
import pandas as pd
df = pd.DataFrame({
    "Customer": ["John", "Alice", "John", "Bob", "Alice"],
    "City": ["Mumbai", "Pune", "Mumbai", "Delhi", "Pune"],
    "Sales": [1200, 2500, 1200, 1800, 2500]
})

df

  Customer    City  Sales
0     John  Mumbai   1200
1    Alice    Pune   2500
2     John  Mumbai   1200
3      Bob   Delhi   1800
4    Alice    Pune   2500

In [3]:
df.duplicated()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [6]:
df[df.duplicated()]

  Customer    City  Sales
2     John  Mumbai   1200
4    Alice    Pune   2500

In [11]:
df.duplicated().sum()

np.int64(2)

In [12]:
# Duplicate Based on Specific Columns
df.duplicated(subset=["Customer"])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [13]:
df.duplicated(subset=["Customer","City"])

0    False
1    False
2     True
3    False
4     True
dtype: bool

# drop_duplicates()

The `drop_duplicates()` method is used to remove duplicate rows from a DataFrame. By default, it keeps the first occurrence of each duplicate and removes the remaining ones.

In [14]:
import pandas as pd

df = pd.DataFrame({
    "Customer": ["John", "Alice", "John", "Bob", "Alice"],
    "City": ["Mumbai", "Pune", "Mumbai", "Delhi", "Pune"],
    "Sales": [1200, 2500, 1200, 1800, 2500]
})

df

  Customer    City  Sales
0     John  Mumbai   1200
1    Alice    Pune   2500
2     John  Mumbai   1200
3      Bob   Delhi   1800
4    Alice    Pune   2500

In [15]:
df.duplicated()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [18]:
df.drop_duplicates()

  Customer    City  Sales
0     John  Mumbai   1200
1    Alice    Pune   2500
3      Bob   Delhi   1800

In [19]:
df

  Customer    City  Sales
0     John  Mumbai   1200
1    Alice    Pune   2500
2     John  Mumbai   1200
3      Bob   Delhi   1800
4    Alice    Pune   2500

In [26]:
df.drop_duplicates(keep="first",ignore_index=True)

  Customer    City  Sales
0     John  Mumbai   1200
1    Alice    Pune   2500
2      Bob   Delhi   1800

In [28]:
df.drop_duplicates(subset=["Customer"], keep="last",ignore_index=True)

  Customer    City  Sales
0     John  Mumbai   1200
1      Bob   Delhi   1800
2    Alice    Pune   2500

In [24]:
df.drop_duplicates(keep=False)

  Customer   City  Sales
3      Bob  Delhi   1800

In [29]:
df.drop_duplicates(subset=["Customer"],ignore_index=True)

  Customer    City  Sales
0     John  Mumbai   1200
1    Alice    Pune   2500
2      Bob   Delhi   1800

# Outliers

Outliers are data points that are significantly different from the rest of the observations in a dataset. They can occur due to data entry errors, measurement errors, or genuine extreme values, and may affect statistical analysis and machine learning models.

In [30]:
import pandas as pd
df = pd.DataFrame({
    "Salary": [45000, 50000, 48000, 52000, 47000, 49000, 500000]
})
df

   Salary
0   45000
1   50000
2   48000
3   52000
4   47000
5   49000
6  500000

In [33]:
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)
print(Q1)
print(Q3)
IQR = Q3 - Q1
print(IQR)

47500.0
51000.0
3500.0

In [34]:
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
print(lower)
print(upper)

42250.0
56250.0

In [35]:
df[
    (df["Salary"] < lower) |
    (df["Salary"] > upper)
]

   Salary
6  500000

# rename()

The `rename()` method is used to change the names of columns or index labels in a Pandas DataFrame without modifying the actual data.

df.rename(columns={"old_name": "new_name"})

In [36]:
import pandas as pd
df = pd.DataFrame({
    "emp_id": [101, 102, 103],
    "emp_name": ["John", "Alice", "Rohit"],
    "sal": [50000, 60000, 45000]
})
df

   emp_id emp_name    sal
0     101     John  50000
1     102    Alice  60000
2     103    Rohit  45000

In [38]:
df.rename(columns={"sal":"Salary"})

   emp_id emp_name  Salary
0     101     John   50000
1     102    Alice   60000
2     103    Rohit   45000

In [40]:
df  #Original Dataframe is not changed

   emp_id emp_name    sal
0     101     John  50000
1     102    Alice  60000
2     103    Rohit  45000

In [41]:
df.rename(columns={
    "emp_id": "Employee_ID",
    "emp_name": "Employee_Name",
    "sal": "Salary"
})

   Employee_ID Employee_Name  Salary
0          101          John   50000
1          102         Alice   60000
2          103         Rohit   45000

In [43]:
df.rename(index={
    0:"A",
    1:"B",
    2:"C"
})

   emp_id emp_name    sal
A     101     John  50000
B     102    Alice  60000
C     103    Rohit  45000

In [44]:
df.rename(
    index={0: "First"},
    columns={"sal": "Salary"}
)

       emp_id emp_name  Salary
First     101     John   50000
1         102    Alice   60000
2         103    Rohit   45000

# replace()

The `replace()` method is used to replace specific values in a Pandas Series or DataFrame with new values. It is commonly used to correct incorrect, inconsistent, or unwanted data.

df.replace(old_value, new_value)

In [45]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["John", "Alice", "Rohit", "Jane"],
    "City": ["pune", "Mumbai", "PUNE", "pune"],
    "Gender": ["M", "F", "M", "F"]
})
df

    Name    City Gender
0   John    pune      M
1  Alice  Mumbai      F
2  Rohit    PUNE      M
3   Jane    pune      F

In [46]:
df.replace("pune", "Pune")

    Name    City Gender
0   John    Pune      M
1  Alice  Mumbai      F
2  Rohit    PUNE      M
3   Jane    Pune      F

In [47]:
df.replace({
    "M": "Male",
    "F": "Female"
})

    Name    City  Gender
0   John    pune    Male
1  Alice  Mumbai  Female
2  Rohit    PUNE    Male
3   Jane    pune  Female

In [48]:
df

    Name    City Gender
0   John    pune      M
1  Alice  Mumbai      F
2  Rohit    PUNE      M
3   Jane    pune      F

In [49]:
df.replace({
    "pune": "Pune",
    "PUNE": "Pune",
    "M": "Male",
    "F": "Female"
})

    Name    City  Gender
0   John    Pune    Male
1  Alice  Mumbai  Female
2  Rohit    Pune    Male
3   Jane    Pune  Female

In [50]:
df

    Name    City Gender
0   John    pune      M
1  Alice  Mumbai      F
2  Rohit    PUNE      M
3   Jane    pune      F

In [52]:
df["Gender"] = df["Gender"].replace({
    "M":"Male",
    "F":"Female"
})

In [53]:
df

    Name    City  Gender
0   John    pune    Male
1  Alice  Mumbai  Female
2  Rohit    PUNE    Male
3   Jane    pune  Female

In [54]:
df["City"] = df["City"].replace({
    "pune": "Pune",
    "PUNE": "Pune"
})

In [55]:
df

    Name    City  Gender
0   John    Pune    Male
1  Alice  Mumbai  Female
2  Rohit    Pune    Male
3   Jane    Pune  Female

In [56]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Customer": ["John", "Alice", "Rohit", "Jane", "David"],
    "City": ["Mumbai", "N/A", "Pune", "Unknown", "Delhi"],
    "Age": [25, "-", 30, 28, "N/A"]
})
df

  Customer     City  Age
0     John   Mumbai   25
1    Alice      N/A    -
2    Rohit     Pune   30
3     Jane  Unknown   28
4    David    Delhi  N/A

In [58]:
df.isnull().sum()  #Pandas reports 0 missing values because "N/A", "Unknown", and "-" are just text.

Customer    0
City        0
Age         0
dtype: int64

In [59]:
df = df.replace({
    "N/A": np.nan,
    "Unknown": np.nan,
    "-": np.nan
})
df

C:\Users\armaa\AppData\Local\Temp\ipykernel_23168\2890155181.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({

  Customer    City   Age
0     John  Mumbai  25.0
1    Alice     NaN   NaN
2    Rohit    Pune  30.0
3     Jane     NaN  28.0
4    David   Delhi   NaN

In [63]:
df = df.replace({
    "N/A": np.nan,
    "Unknown": np.nan,
    "-": np.nan
})
df["Age"] = pd.to_numeric(df["Age"])
df

  Customer    City   Age
0     John  Mumbai  25.0
1    Alice     NaN   NaN
2    Rohit    Pune  30.0
3     Jane     NaN  28.0
4    David   Delhi   NaN

# Real-World Data Cleaning Workflow

In real-world projects, datasets often contain duplicate records, inconsistent values, poorly named columns, and outliers. Before performing any analysis, these issues should be identified and corrected to ensure accurate results.

This workflow demonstrates how to clean a messy dataset using common Pandas techniques.

In [64]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "cust_name": ["John", "Alice", "John", "Bob", "David", "Jane"],
    "city": ["pune", "Mumbai", "pune", "Delhi", "Unknown", "PUNE"],
    "gender": ["M", "F", "M", "M", "F", "F"],
    "sales": [1200, 2500, 1200, 1800, 500000, 2200]
})

df

  cust_name     city gender   sales
0      John     pune      M    1200
1     Alice   Mumbai      F    2500
2      John     pune      M    1200
3       Bob    Delhi      M    1800
4     David  Unknown      F  500000
5      Jane     PUNE      F    2200

In [69]:
df = df.drop_duplicates(ignore_index=True)

In [70]:
df = df.replace({
    "pune": "Pune",
    "PUNE": "Pune",
    "Unknown": np.nan,
    "M": "Male",
    "F": "Female"
})
df

  Customer_Name    City  Gender   Sales
0          John    Pune    Male    1200
1         Alice  Mumbai  Female    2500
2           Bob   Delhi    Male    1800
3         David     NaN  Female  500000
4          Jane    Pune  Female    2200

In [71]:
df = df.rename(columns={
    "cust_name": "Customer_Name",
    "city": "City",
    "gender": "Gender",
    "sales": "Sales"
})
df

  Customer_Name    City  Gender   Sales
0          John    Pune    Male    1200
1         Alice  Mumbai  Female    2500
2           Bob   Delhi    Male    1800
3         David     NaN  Female  500000
4          Jane    Pune  Female    2200

In [73]:
Q1 = df["Sales"].quantile(0.25)
Q3 = df["Sales"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

In [74]:
df = df[
    (df["Sales"] >= lower) &
    (df["Sales"] <= upper)
]
df

  Customer_Name    City  Gender  Sales
0          John    Pune    Male   1200
1         Alice  Mumbai  Female   2500
2           Bob   Delhi    Male   1800
4          Jane    Pune  Female   2200

In [75]:
df.isnull().sum()

Customer_Name    0
City             0
Gender           0
Sales            0
dtype: int64