# Real World Data Analysis

Real World Data Analysis involves exploring, cleaning, transforming, and analyzing business data to answer practical questions and support decision-making. Instead of learning individual functions, the focus is on solving real business problems using a complete data analysis workflow.

In [1]:
import pandas as pd
df = pd.DataFrame({
    "Order_ID": [101,102,103,104,105,106,107,108,109,110],
    "Customer": ["John","Alice","Bob","John","David","Alice","Eva","Frank","Grace","Henry"],
    "Region": ["North","South","East","North","West","South","East","West","North","South"],
    "Category": ["Electronics","Furniture","Electronics","Clothing","Furniture",
                 "Electronics","Clothing","Furniture","Electronics","Clothing"],
    "Product": ["Laptop","Chair","Phone","T-Shirt","Table",
                "Headphones","Jeans","Sofa","Tablet","Jacket"],
    "Salesperson": ["Amit","Neha","Amit","Raj","Neha",
                    "Raj","Amit","Neha","Raj","Amit"],
    "Quantity": [2,4,3,5,2,6,4,1,3,2],
    "Price": [50000,7000,30000,1200,15000,2500,1800,40000,28000,3500],
    "Discount": [10,5,15,0,8,5,0,20,10,5],
    "Order_Date": pd.to_datetime([
        "2024-01-15","2024-01-20","2024-02-10","2024-02-18",
        "2024-03-05","2024-03-12","2024-04-01","2024-04-18",
        "2024-05-09","2024-05-25"
    ])
})
df

,Order_ID,Customer,Region,Category,Product,Salesperson,Quantity,Price,Discount,Order_Date
0,101,John,North,Electronics,Laptop,Amit,2,50000,10,2024-01-15
1,102,Alice,South,Furniture,Chair,Neha,4,7000,5,2024-01-20
2,103,Bob,East,Electronics,Phone,Amit,3,30000,15,2024-02-10
3,104,John,North,Clothing,T-Shirt,Raj,5,1200,0,2024-02-18
4,105,David,West,Furniture,Table,Neha,2,15000,8,2024-03-05
5,106,Alice,South,Electronics,Headphones,Raj,6,2500,5,2024-03-12
6,107,Eva,East,Clothing,Jeans,Amit,4,1800,0,2024-04-01
7,108,Frank,West,Furniture,Sofa,Neha,1,40000,20,2024-04-18
8,109,Grace,North,Electronics,Tablet,Raj,3,28000,10,2024-05-09
9,110,Henry,South,Clothing,Jacket,Amit,2,3500,5,2024-05-25

In [2]:
df.head()

,Order_ID,Customer,Region,Category,Product,Salesperson,Quantity,Price,Discount,Order_Date
0,101,John,North,Electronics,Laptop,Amit,2,50000,10,2024-01-15
1,102,Alice,South,Furniture,Chair,Neha,4,7000,5,2024-01-20
2,103,Bob,East,Electronics,Phone,Amit,3,30000,15,2024-02-10
3,104,John,North,Clothing,T-Shirt,Raj,5,1200,0,2024-02-18
4,105,David,West,Furniture,Table,Neha,2,15000,8,2024-03-05

In [3]:
df.tail()

,Order_ID,Customer,Region,Category,Product,Salesperson,Quantity,Price,Discount,Order_Date
5,106,Alice,South,Electronics,Headphones,Raj,6,2500,5,2024-03-12
6,107,Eva,East,Clothing,Jeans,Amit,4,1800,0,2024-04-01
7,108,Frank,West,Furniture,Sofa,Neha,1,40000,20,2024-04-18
8,109,Grace,North,Electronics,Tablet,Raj,3,28000,10,2024-05-09
9,110,Henry,South,Clothing,Jacket,Amit,2,3500,5,2024-05-25

In [5]:
df.shape

(10, 10)

In [7]:
df.columns

Index(['Order_ID', 'Customer', 'Region', 'Category', 'Product', 'Salesperson',
       'Quantity', 'Price', 'Discount', 'Order_Date'],
      dtype='object')

In [8]:
df.dtypes

Order_ID                int64
Customer               object
Region                 object
Category               object
Product                object
Salesperson            object
Quantity                int64
Price                   int64
Discount                int64
Order_Date     datetime64[ns]
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     10 non-null     int64
 1   Customer     10 non-null     object
 2   Region       10 non-null     object
 3   Category     10 non-null     object
 4   Product      10 non-null     object
 5   Salesperson  10 non-null     object
 6   Quantity     10 non-null     int64
 7   Price        10 non-null     int64
 8   Discount     10 non-null     int64
 9   Order_Date   10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 932.0+ bytes

In [13]:
df.describe()

        Order_ID   Quantity         Price   Discount           Order_Date
count   10.00000  10.000000     10.000000  10.000000                   10
mean   105.50000   3.200000  17900.000000   7.800000  2024-03-13 21:36:00
min    101.00000   1.000000   1200.000000   0.000000  2024-01-15 00:00:00
25%    103.25000   2.000000   2750.000000   5.000000  2024-02-12 00:00:00
50%    105.50000   3.000000  11000.000000   6.500000  2024-03-08 12:00:00
75%    107.75000   4.000000  29500.000000  10.000000  2024-04-13 18:00:00
max    110.00000   6.000000  50000.000000  20.000000  2024-05-25 00:00:00
std      3.02765   1.549193  17879.473022   6.285786                  NaN

In [14]:
df.describe(include="object")

       Customer Region     Category Product Salesperson
count        10     10           10      10          10
unique        8      4            3      10           3
top        John  North  Electronics  Laptop        Amit
freq          2      3            4       1           4

In [15]:
df.isnull().sum()

Order_ID       0
Customer       0
Region         0
Category       0
Product        0
Salesperson    0
Quantity       0
Price          0
Discount       0
Order_Date     0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df["Revenue"] = df["Quantity"] * df["Price"]
df

,Order_ID,Customer,Region,Category,Product,Salesperson,Quantity,Price,Discount,Order_Date,Revenue
0,101,John,North,Electronics,Laptop,Amit,2,50000,10,2024-01-15,100000
1,102,Alice,South,Furniture,Chair,Neha,4,7000,5,2024-01-20,28000
2,103,Bob,East,Electronics,Phone,Amit,3,30000,15,2024-02-10,90000
3,104,John,North,Clothing,T-Shirt,Raj,5,1200,0,2024-02-18,6000
4,105,David,West,Furniture,Table,Neha,2,15000,8,2024-03-05,30000
5,106,Alice,South,Electronics,Headphones,Raj,6,2500,5,2024-03-12,15000
6,107,Eva,East,Clothing,Jeans,Amit,4,1800,0,2024-04-01,7200
7,108,Frank,West,Furniture,Sofa,Neha,1,40000,20,2024-04-18,40000
8,109,Grace,North,Electronics,Tablet,Raj,3,28000,10,2024-05-09,84000
9,110,Henry,South,Clothing,Jacket,Amit,2,3500,5,2024-05-25,7000

In [18]:
df["Discount_Amount"] = (
    df["Revenue"] * df["Discount"] / 100
)
df

,Order_ID,Customer,Region,Category,Product,Salesperson,Quantity,Price,Discount,Order_Date,Revenue,Discount_Amount
0,101,John,North,Electronics,Laptop,Amit,2,50000,10,2024-01-15,100000,10000.0
1,102,Alice,South,Furniture,Chair,Neha,4,7000,5,2024-01-20,28000,1400.0
2,103,Bob,East,Electronics,Phone,Amit,3,30000,15,2024-02-10,90000,13500.0
3,104,John,North,Clothing,T-Shirt,Raj,5,1200,0,2024-02-18,6000,0.0
4,105,David,West,Furniture,Table,Neha,2,15000,8,2024-03-05,30000,2400.0
5,106,Alice,South,Electronics,Headphones,Raj,6,2500,5,2024-03-12,15000,750.0
6,107,Eva,East,Clothing,Jeans,Amit,4,1800,0,2024-04-01,7200,0.0
7,108,Frank,West,Furniture,Sofa,Neha,1,40000,20,2024-04-18,40000,8000.0
8,109,Grace,North,Electronics,Tablet,Raj,3,28000,10,2024-05-09,84000,8400.0
9,110,Henry,South,Clothing,Jacket,Amit,2,3500,5,2024-05-25,7000,350.0

In [19]:
df["Final_Amount"] = (
    df["Revenue"] - df["Discount_Amount"]
)
df

,Order_ID,Customer,Region,Category,Product,Salesperson,Quantity,Price,Discount,Order_Date,Revenue,Discount_Amount,Final_Amount
0,101,John,North,Electronics,Laptop,Amit,2,50000,10,2024-01-15,100000,10000.0,90000.0
1,102,Alice,South,Furniture,Chair,Neha,4,7000,5,2024-01-20,28000,1400.0,26600.0
2,103,Bob,East,Electronics,Phone,Amit,3,30000,15,2024-02-10,90000,13500.0,76500.0
3,104,John,North,Clothing,T-Shirt,Raj,5,1200,0,2024-02-18,6000,0.0,6000.0
4,105,David,West,Furniture,Table,Neha,2,15000,8,2024-03-05,30000,2400.0,27600.0
5,106,Alice,South,Electronics,Headphones,Raj,6,2500,5,2024-03-12,15000,750.0,14250.0
6,107,Eva,East,Clothing,Jeans,Amit,4,1800,0,2024-04-01,7200,0.0,7200.0
7,108,Frank,West,Furniture,Sofa,Neha,1,40000,20,2024-04-18,40000,8000.0,32000.0
8,109,Grace,North,Electronics,Tablet,Raj,3,28000,10,2024-05-09,84000,8400.0,75600.0
9,110,Henry,South,Clothing,Jacket,Amit,2,3500,5,2024-05-25,7000,350.0,6650.0

# Business Question 1

## Which products generate the highest revenue?

Businesses analyze product revenue to identify their best-selling and highest-earning products. This helps management make decisions about inventory, marketing, pricing, and future investments.

In [20]:
df.groupby("Product")

In [21]:
df.groupby("Product")["Revenue"].sum()

Product
Chair          28000
Headphones     15000
Jacket          7000
Jeans           7200
Laptop        100000
Phone          90000
Sofa           40000
T-Shirt         6000
Table          30000
Tablet         84000
Name: Revenue, dtype: int64

In [22]:
df.groupby("Product")["Revenue"].sum().sort_values(ascending=False)

Product
Laptop        100000
Phone          90000
Tablet         84000
Sofa           40000
Table          30000
Chair          28000
Headphones     15000
Jeans           7200
Jacket          7000
T-Shirt         6000
Name: Revenue, dtype: int64

In [31]:
product_revenue = (
    df.groupby("Product")["Revenue"]
      .sum()
      .sort_values(ascending=False)
)
product_revenue

Product
Laptop        100000
Phone          90000
Tablet         84000
Sofa           40000
Table          30000
Chair          28000
Headphones     15000
Jeans           7200
Jacket          7000
T-Shirt         6000
Name: Revenue, dtype: int64

# Business Question 2

## Which region generates the highest revenue?
m
Regional sales analysis helps businesses identify high-performing and low-performing markets. This information is useful for allocating marketing budgets, planning inventory, and expanding operations.

In [27]:
df.groupby("Region")

In [28]:
df.groupby("Region")["Revenue"].sum()

Region
East      97200
North    190000
South     50000
West      70000
Name: Revenue, dtype: int64

In [29]:
region_revenue = (
    df.groupby("Region")["Revenue"]
      .sum()
      .sort_values(ascending=False)
)
region_revenue

Region
North    190000
East      97200
West      70000
South     50000
Name: Revenue, dtype: int64

In [32]:
df.groupby("Region")["Order_ID"].count()

Region
East     2
North    3
South    3
West     2
Name: Order_ID, dtype: int64

In [36]:
df.groupby("Region").agg({
    "Revenue": "sum",
    "Order_ID": "count"
})

        Revenue  Order_ID
Region
East      97200         2
North    190000         3
South     50000         3
West      70000         2

In [37]:
region_summary = (
    df.groupby("Region")
      .agg({
          "Revenue": "sum",
          "Order_ID": "count"
      })
      .sort_values("Revenue", ascending=False)
)

region_summary

        Revenue  Order_ID
Region
North    190000         3
East      97200         2
West      70000         2
South     50000         3

# Business Question 3

## Which product category generates the highest revenue?

Businesses categorize products into groups such as Electronics, Furniture, and Clothing. Analyzing revenue by category helps management understand which product segments contribute the most to overall sales and where future investments should be made.

In [38]:
df.groupby("Category")

In [39]:
df.groupby("Category")["Revenue"].sum()

Category
Clothing        20200
Electronics    289000
Furniture       98000
Name: Revenue, dtype: int64

In [40]:
category_revenue = (
    df.groupby("Category")["Revenue"]
      .sum()
      .sort_values(ascending=False)
)
category_revenue

Category
Electronics    289000
Furniture       98000
Clothing        20200
Name: Revenue, dtype: int64

In [41]:
df.groupby("Category")["Order_ID"].count()

Category
Clothing       3
Electronics    4
Furniture      3
Name: Order_ID, dtype: int64

In [42]:
category_summary = (
    df.groupby("Category")
      .agg({
          "Revenue": "sum",
          "Order_ID": "count"
      })
      .sort_values("Revenue", ascending=False)
)
category_summary

             Revenue  Order_ID
Category
Electronics   289000         4
Furniture      98000         3
Clothing       20200         3

# Business Question 4

## Which salesperson generated the highest revenue?

Sales performance analysis helps businesses evaluate employee performance, identify top performers, design incentive programs, and provide additional training where needed.

In [43]:
df.groupby("Salesperson")

In [44]:
df.groupby("Salesperson")["Revenue"].sum()

Salesperson
Amit    204200
Neha     98000
Raj     105000
Name: Revenue, dtype: int64

In [45]:
salesperson_revenue = (
    df.groupby("Salesperson")["Revenue"]
      .sum()
      .sort_values(ascending=False)
)
salesperson_revenue

Salesperson
Amit    204200
Raj     105000
Neha     98000
Name: Revenue, dtype: int64

In [46]:
df.groupby("Salesperson")["Order_ID"].count()

Salesperson
Amit    4
Neha    3
Raj     3
Name: Order_ID, dtype: int64

In [47]:
df.groupby("Salesperson").agg({
    "Revenue": "sum",
    "Order_ID": "count"
})

             Revenue  Order_ID
Salesperson
Amit          204200         4
Neha           98000         3
Raj           105000         3

In [48]:
df.groupby("Salesperson").agg({
    "Revenue": ["sum", "mean"],
    "Order_ID": "count"
})

            Revenue               Order_ID
                sum          mean    count
Salesperson
Amit         204200  51050.000000        4
Neha          98000  32666.666667        3
Raj          105000  35000.000000        3

In [52]:
sales_summary = (
    df.groupby("Salesperson")
      .agg(
          Total_Revenue=("Revenue", "sum"),
          Orders=("Order_ID", "count"),
          Average_Revenue=("Revenue", "mean")
      )
      .sort_values("Total_Revenue", ascending=False)
)
sales_summary

             Total_Revenue  Orders  Average_Revenue
Salesperson
Amit                204200       4     51050.000000
Raj                 105000       3     35000.000000
Neha                 98000       3     32666.666667

# Business Question 5

## How does revenue change over time?

Businesses monitor monthly sales trends to identify seasonality, growth patterns, and periods of high or low performance. This analysis helps in forecasting, inventory planning, and marketing decisions.

In [53]:
df["Month"] = df["Order_Date"].dt.month
df[["Order_Date", "Month"]]

  Order_Date  Month
0 2024-01-15      1
1 2024-01-20      1
2 2024-02-10      2
3 2024-02-18      2
4 2024-03-05      3
5 2024-03-12      3
6 2024-04-01      4
7 2024-04-18      4
8 2024-05-09      5
9 2024-05-25      5

In [54]:
df["Month_Name"] = df["Order_Date"].dt.month_name()
df[["Order_Date", "Month_Name"]]

  Order_Date Month_Name
0 2024-01-15    January
1 2024-01-20    January
2 2024-02-10   February
3 2024-02-18   February
4 2024-03-05      March
5 2024-03-12      March
6 2024-04-01      April
7 2024-04-18      April
8 2024-05-09        May
9 2024-05-25        May

In [55]:
df.groupby("Month_Name")["Revenue"].sum()

Month_Name
April        47200
February     96000
January     128000
March        45000
May          91000
Name: Revenue, dtype: int64

In [58]:
monthly_revenue = (
    df.groupby(["Month", "Month_Name"])["Revenue"]
      .sum()
      .reset_index()
)
monthly_revenue

   Month Month_Name  Revenue
0      1    January   128000
1      2   February    96000
2      3      March    45000
3      4      April    47200
4      5        May    91000

In [59]:
monthly_revenue = (
    df.groupby(["Month", "Month_Name"])["Revenue"]
      .sum()
      .reset_index()
      .drop(columns="Month")
)
monthly_revenue

  Month_Name  Revenue
0    January   128000
1   February    96000
2      March    45000
3      April    47200
4        May    91000

In [60]:
monthly_revenue.sort_values(
    by="Revenue",
    ascending=False
)

  Month_Name  Revenue
0    January   128000
1   February    96000
4        May    91000
3      April    47200
2      March    45000

# Business Question 6

## Which customers spend the most?

Customer spending analysis helps businesses identify high-value customers. These customers can be targeted with loyalty programs, personalized offers, and premium services to improve customer retention and increase revenue.

In [61]:
df.groupby("Customer")

In [62]:
df.groupby("Customer")["Revenue"].sum()

Customer
Alice     43000
Bob       90000
David     30000
Eva        7200
Frank     40000
Grace     84000
Henry      7000
John     106000
Name: Revenue, dtype: int64

In [63]:
top_customers = (
    df.groupby("Customer")["Revenue"]
      .sum()
      .sort_values(ascending=False)
      .head(5)
)

top_customers

Customer
John     106000
Bob       90000
Grace     84000
Alice     43000
Frank     40000
Name: Revenue, dtype: int64

In [64]:
df.groupby("Customer")["Order_ID"].count()

Customer
Alice    2
Bob      1
David    1
Eva      1
Frank    1
Grace    1
Henry    1
John     2
Name: Order_ID, dtype: int64

In [65]:
customer_summary = (
    df.groupby("Customer")
      .agg(
          Total_Revenue=("Revenue", "sum"),
          Orders=("Order_ID", "count"),
          Average_Order_Value=("Revenue", "mean")
      )
      .sort_values("Total_Revenue", ascending=False)
)
customer_summary

          Total_Revenue  Orders  Average_Order_Value
Customer
John             106000       2              53000.0
Bob               90000       1              90000.0
Grace             84000       1              84000.0
Alice             43000       2              21500.0
Frank             40000       1              40000.0
David             30000       1              30000.0
Eva                7200       1               7200.0
Henry              7000       1               7000.0

# Business Question 7

## How are discounts affecting sales?

Businesses frequently offer discounts to attract customers and increase sales. Analyzing discount patterns helps determine whether discounts are being used effectively and whether certain products, categories, or regions receive higher discounts than others.

In [66]:
df["Discount"].max()

20

In [67]:
df[df["Discount"] == df["Discount"].max()]

,Order_ID,Customer,Region,Category,Product,Salesperson,Quantity,Price,Discount,Order_Date,Revenue,Discount_Amount,Final_Amount,Month,Month_Name
7,108,Frank,West,Furniture,Sofa,Neha,1,40000,20,2024-04-18,40000,8000.0,32000.0,4,April

In [68]:
df["Discount"].mean()

np.float64(7.8)

In [69]:
df.groupby("Category")["Discount"].mean()

Category
Clothing        1.666667
Electronics    10.000000
Furniture      11.000000
Name: Discount, dtype: float64

In [70]:
df.groupby("Region")["Discount"].mean()

Region
East      7.500000
North     6.666667
South     5.000000
West     14.000000
Name: Discount, dtype: float64

In [71]:
discount_summary = (
    df.groupby("Category")
      .agg(
          Average_Discount=("Discount", "mean"),
          Maximum_Discount=("Discount", "max"),
          Orders=("Order_ID", "count")
      )
      .sort_values("Average_Discount", ascending=False)
)
discount_summary

             Average_Discount  Maximum_Discount  Orders
Category
Furniture           11.000000                20       3
Electronics         10.000000                15       4
Clothing             1.666667                 5       3

# Management Summary Report

Managers do not usually look at raw data. Instead, they prefer concise summary reports that highlight key performance indicators (KPIs). Using `groupby()`, `agg()`, and `pivot_table()`, we can create reports that support business decision-making.

In [72]:
region_report = (
    df.groupby("Region")
      .agg(
          Total_Revenue=("Revenue", "sum"),
          Total_Orders=("Order_ID", "count"),
          Average_Discount=("Discount", "mean")
      )
      .sort_values("Total_Revenue", ascending=False)
)

region_report

        Total_Revenue  Total_Orders  Average_Discount
Region
North          190000             3          6.666667
East            97200             2          7.500000
West            70000             2         14.000000
South           50000             3          5.000000

In [73]:
category_report = (
    df.groupby("Category")
      .agg(
          Total_Revenue=("Revenue", "sum"),
          Orders=("Order_ID", "count"),
          Average_Discount=("Discount", "mean")
      )
      .sort_values("Total_Revenue", ascending=False)
)
category_report

             Total_Revenue  Orders  Average_Discount
Category
Electronics         289000       4         10.000000
Furniture            98000       3         11.000000
Clothing             20200       3          1.666667

In [74]:
salesperson_report = (
    df.groupby("Salesperson")
      .agg(
          Total_Revenue=("Revenue", "sum"),
          Orders=("Order_ID", "count"),
          Average_Revenue=("Revenue", "mean")
      )
      .sort_values("Total_Revenue", ascending=False)
)
salesperson_report

             Total_Revenue  Orders  Average_Revenue
Salesperson
Amit                204200       4     51050.000000
Raj                 105000       3     35000.000000
Neha                 98000       3     32666.666667

In [75]:
customer_report = (
    df.groupby("Customer")
      .agg(
          Total_Revenue=("Revenue", "sum"),
          Orders=("Order_ID", "count")
      )
      .sort_values("Total_Revenue", ascending=False)
)
customer_report

          Total_Revenue  Orders
Customer
John             106000       2
Bob               90000       1
Grace             84000       1
Alice             43000       2
Frank             40000       1
David             30000       1
Eva                7200       1
Henry              7000       1

In [76]:
pivot = pd.pivot_table(
    df,
    values="Revenue",
    index="Region",
    columns="Category",
    aggfunc="sum",
    fill_value=0
)
pivot

Category  Clothing  Electronics  Furniture
Region
East          7200        90000          0
North         6000       184000          0
South         7000        15000      28000
West             0            0      70000

In [77]:
print("Total Revenue:", df["Revenue"].sum())
print("Total Orders:", df["Order_ID"].count())
print("Average Revenue:", df["Revenue"].mean())
print("Maximum Revenue:", df["Revenue"].max())
print("Minimum Revenue:", df["Revenue"].min())

Total Revenue: 407200
Total Orders: 10
Average Revenue: 40720.0
Maximum Revenue: 100000
Minimum Revenue: 6000