# Notebook 17 – Exploratory Data Analysis (EDA)

## Dataset Creation

To understand Exploratory Data Analysis (EDA), we need a realistic dataset.

In this notebook, we'll use a retail sales dataset containing information about:

- Order ID
- Customer Name
- Region
- Category
- Product
- Salesperson
- Quantity
- Price
- Discount
- Order Date

We'll also create business metrics such as Revenue and Final Amount that will be used throughout the notebook.

In [1]:
import pandas as pd

In [2]:
data = {
    "Order_ID": [101,102,103,104,105,106,107,108,109,110,
                 111,112,113,114,115,116,117,118,119,120],

    "Customer": [
        "John","Alice","Bob","David","Eva",
        "Frank","Grace","Henry","Ivy","Jack",
        "Kevin","Lily","Mike","Nina","Oscar",
        "Peter","Queen","Ryan","Sophia","Tom"
    ],

    "Region": [
        "North","South","East","West","North",
        "South","East","West","North","South",
        "East","West","North","South","East",
        "West","North","South","East","West"
    ],

    "Category": [
        "Electronics","Furniture","Electronics","Clothing","Furniture",
        "Electronics","Clothing","Furniture","Electronics","Clothing",
        "Furniture","Electronics","Clothing","Furniture","Electronics",
        "Clothing","Furniture","Electronics","Clothing","Furniture"
    ],

    "Product": [
        "Laptop","Chair","Phone","T-Shirt","Table",
        "Tablet","Jeans","Sofa","Headphones","Jacket",
        "Desk","Monitor","Shoes","Bed","Camera",
        "Cap","Cupboard","Printer","Shirt","Dining Table"
    ],

    "Salesperson": [
        "Amit","Neha","Raj","Amit","Neha",
        "Raj","Amit","Neha","Raj","Amit",
        "Neha","Raj","Amit","Neha","Raj",
        "Amit","Neha","Raj","Amit","Neha"
    ],

    "Quantity": [
        2,4,3,5,2,
        1,6,2,4,3,
        2,1,5,1,2,
        7,1,2,4,1
    ],

    "Price": [
        50000,7000,30000,1200,15000,
        40000,1800,25000,6000,2000,
        18000,22000,3500,45000,38000,
        800,30000,20000,1500,55000
    ],

    "Discount": [
        10,5,15,0,8,
        12,5,20,10,0,
        7,15,5,18,10,
        0,12,8,5,15
    ],

    "Order_Date": [
        "2024-01-10","2024-01-15","2024-01-22","2024-02-05","2024-02-14",
        "2024-02-28","2024-03-08","2024-03-15","2024-03-25","2024-04-02",
        "2024-04-10","2024-04-18","2024-05-05","2024-05-16","2024-05-27",
        "2024-06-04","2024-06-14","2024-06-22","2024-07-08","2024-07-18"
    ]
}

df = pd.DataFrame(data)

In [3]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [8]:
df["Revenue"] = df["Quantity"] * df["Price"]

df["Discount_Amount"] = (
    df["Revenue"] * df["Discount"] / 100
)

df["Final_Amount"] = (
    df["Revenue"] - df["Discount_Amount"]
)

In [9]:
df

,Order_ID,Customer,Region,Category,Product,Salesperson,Quantity,Price,Discount,Order_Date,Revenue,Discount_Amount,Final_Amount
0,101,John,North,Electronics,Laptop,Amit,2,50000,10,2024-01-10,100000,10000.0,90000.0
1,102,Alice,South,Furniture,Chair,Neha,4,7000,5,2024-01-15,28000,1400.0,26600.0
2,103,Bob,East,Electronics,Phone,Raj,3,30000,15,2024-01-22,90000,13500.0,76500.0
3,104,David,West,Clothing,T-Shirt,Amit,5,1200,0,2024-02-05,6000,0.0,6000.0
4,105,Eva,North,Furniture,Table,Neha,2,15000,8,2024-02-14,30000,2400.0,27600.0
5,106,Frank,South,Electronics,Tablet,Raj,1,40000,12,2024-02-28,40000,4800.0,35200.0
6,107,Grace,East,Clothing,Jeans,Amit,6,1800,5,2024-03-08,10800,540.0,10260.0
7,108,Henry,West,Furniture,Sofa,Neha,2,25000,20,2024-03-15,50000,10000.0,40000.0
8,109,Ivy,North,Electronics,Headphones,Raj,4,6000,10,2024-03-25,24000,2400.0,21600.0
9,110,Jack,South,Clothing,Jacket,Amit,3,2000,0,2024-04-02,6000,0.0,6000.0
10,111,Kevin,East,Furniture,Desk,Neha,2,18000,7,2024-04-10,36000,2520.0,33480.0
11,112,Lily,West,Electronics,Monitor,Raj,1,22000,15,2024-04-18,22000,3300.0,18700.0
12,113,Mike,North,Clothing,Shoes,Amit,5,3500,5,2024-05-05,17500,875.0,16625.0
13,114,Nina,South,Furniture,Bed,Neha,1,45000,18,2024-05-16,45000,8100.0,36900.0
14,115,Oscar,East,Electronics,Camera,Raj,2,38000,10,2024-05-27,76000,7600.0,68400.0
15,116,Peter,West,Clothing,Cap,Amit,7,800,0,2024-06-04,5600,0.0,5600.0
16,117,Queen,North,Furniture,Cupboard,Neha,1,30000,12,2024-06-14,30000,3600.0,26400.0
17,118,Ryan,South,Electronics,Printer,Raj,2,20000,8,2024-06-22,40000,3200.0,36800.0
18,119,Sophia,East,Clothing,Shirt,Amit,4,1500,5,2024-07-08,6000,300.0,5700.0
19,120,Tom,West,Furniture,Dining Table,Neha,1,55000,15,2024-07-18,55000,8250.0,46750.0

# Univariate Analysis

## What is Univariate Analysis?

Univariate Analysis is the process of analyzing **one variable at a time**.

The main objective is to understand the distribution, frequency, and characteristics of individual variables without considering relationships with other variables.

For numerical variables, we study measures such as minimum, maximum, mean, median, and distribution.

For categorical variables, we analyze unique values, frequencies, and the most common categories.

In [10]:
df["Region"].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [11]:
df["Region"].nunique()

4

In [12]:
df["Region"].value_counts()

Region
North    5
South    5
East     5
West     5
Name: count, dtype: int64

In [13]:
df["Region"].value_counts(normalize=True) * 100

Region
North    25.0
South    25.0
East     25.0
West     25.0
Name: proportion, dtype: float64

In [14]:
df["Category"].value_counts()

Category
Electronics    7
Furniture      7
Clothing       6
Name: count, dtype: int64

In [15]:
df["Salesperson"].value_counts()

Salesperson
Amit    7
Neha    7
Raj     6
Name: count, dtype: int64

In [17]:
df["Revenue"].min()

5600

In [19]:
df["Revenue"].max()

100000

In [20]:
df["Revenue"].mean()

np.float64(35895.0)

In [21]:
df["Revenue"].median()

30000.0

In [22]:
df["Revenue"].std()

27490.88796406241

In [23]:
df["Revenue"].agg([
    "min",
    "max",
    "mean",
    "median",
    "std"
])

min         5600.000000
max       100000.000000
mean       35895.000000
median     30000.000000
std        27490.887964
Name: Revenue, dtype: float64

# Outlier Detection

## What are Outliers?

Outliers are observations that are significantly different from the rest of the data.

These values may represent:

- Data entry errors
- Exceptional business transactions
- Fraudulent activities
- Rare events

Detecting outliers is an important step in Exploratory Data Analysis because they can significantly affect statistical measures such as the mean and standard deviation.

In [26]:
Q1 = df["Revenue"].quantile(0.25)
Q3 = df["Revenue"].quantile(0.75)

print("Q1:", Q1)
print("Q3:", Q3)

Q1: 15825.0
Q3: 46250.0

In [27]:
IQR = Q3 - Q1
print("IQR:", IQR)

IQR: 30425.0

In [28]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

Lower Bound: -29812.5
Upper Bound: 91887.5

In [30]:
outliers = df[
    (df["Revenue"] < lower_bound) |
    (df["Revenue"] > upper_bound)
]
outliers

,Order_ID,Customer,Region,Category,Product,Salesperson,Quantity,Price,Discount,Order_Date,Revenue,Discount_Amount,Final_Amount
0,101,John,North,Electronics,Laptop,Amit,2,50000,10,2024-01-10,100000,10000.0,90000.0

In [31]:
df.loc[0, "Revenue"] = 500000

In [32]:
outliers = df[
    (df["Revenue"] < lower_bound) |
    (df["Revenue"] > upper_bound)
]
outliers

,Order_ID,Customer,Region,Category,Product,Salesperson,Quantity,Price,Discount,Order_Date,Revenue,Discount_Amount,Final_Amount
0,101,John,North,Electronics,Laptop,Amit,2,50000,10,2024-01-10,500000,10000.0,90000.0

In [33]:
df.loc[0, "Revenue"] = (
    df.loc[0, "Quantity"] *
    df.loc[0, "Price"]
)

In [35]:
len(outliers)     #to count no of outlliers

1

# Bivariate Analysis

## What is Bivariate Analysis?

Bivariate Analysis is the process of studying the relationship between **two variables**.

It helps answer questions like:

- Does revenue vary across regions?
- Which category generates the highest revenue?
- Does increasing quantity increase revenue?
- Are higher discounts associated with higher revenue?

The objective is to identify patterns, trends, and relationships between variables.

In [36]:
df.groupby("Region")["Revenue"].sum()

Region
East     218800
North    201500
South    159000
West     138600
Name: Revenue, dtype: int64

In [37]:
df.groupby("Region")["Revenue"] \
  .sum() \
  .sort_values(ascending=False)

Region
East     218800
North    201500
South    159000
West     138600
Name: Revenue, dtype: int64

In [38]:
df.groupby("Category")["Revenue"] \
  .sum() \
  .sort_values(ascending=False)

Category
Electronics    392000
Furniture      274000
Clothing        51900
Name: Revenue, dtype: int64

In [39]:
df.groupby("Salesperson")["Revenue"].sum()

Salesperson
Amit    151900
Neha    274000
Raj     292000
Name: Revenue, dtype: int64

In [40]:
df.groupby("Category")["Revenue"].mean()

Category
Clothing        8650.000000
Electronics    56000.000000
Furniture      39142.857143
Name: Revenue, dtype: float64

In [41]:
df.groupby("Region")["Discount"].mean()

Region
East      8.4
North     9.0
South     8.6
West     10.0
Name: Discount, dtype: float64

In [42]:
df[["Quantity", "Revenue"]]

    Quantity  Revenue
0          2   100000
1          4    28000
2          3    90000
3          5     6000
4          2    30000
5          1    40000
6          6    10800
7          2    50000
8          4    24000
9          3     6000
10         2    36000
11         1    22000
12         5    17500
13         1    45000
14         2    76000
15         7     5600
16         1    30000
17         2    40000
18         4     6000
19         1    55000

In [43]:
df.groupby("Category").agg(
    Total_Revenue=("Revenue", "sum"),
    Average_Revenue=("Revenue", "mean"),
    Average_Discount=("Discount", "mean"),
    Orders=("Order_ID", "count")
)

             Total_Revenue  Average_Revenue  Average_Discount  Orders
Category
Clothing             51900      8650.000000          2.500000       6
Electronics         392000     56000.000000         11.428571       7
Furniture           274000     39142.857143         12.142857       7

# Correlation Analysis

## What is Correlation?

Correlation measures the **strength and direction of the relationship between two numerical variables**.

It helps answer questions like:

- Does increasing quantity increase revenue?
- Does a higher discount lead to higher sales?
- Are price and revenue related?

The correlation coefficient ranges from **-1 to +1**.

- **+1** → Perfect positive correlation
- **0** → No correlation
- **-1** → Perfect negative correlation

In [44]:
numeric_df = df.select_dtypes(include="number")
numeric_df.head()

   Order_ID  Quantity  Price  Discount  Revenue  Discount_Amount  Final_Amount
0       101         2  50000        10   100000          10000.0       90000.0
1       102         4   7000         5    28000           1400.0       26600.0
2       103         3  30000        15    90000          13500.0       76500.0
3       104         5   1200         0     6000              0.0        6000.0
4       105         2  15000         8    30000           2400.0       27600.0

In [45]:
numeric_df.corr()

,Order_ID,Quantity,Price,Discount,Revenue,Discount_Amount,Final_Amount
Order_ID,1.000000,-0.128253,0.077222,0.059595,-0.244407,-0.163583,-0.253864
Quantity,-0.128253,1.000000,-0.776938,-0.721814,-0.514225,-0.550380,-0.499274
Price,0.077222,-0.776938,1.000000,0.739640,0.796333,0.805277,0.781131
Discount,0.059595,-0.721814,0.739640,1.000000,0.597643,0.796319,0.553793
Revenue,-0.244407,-0.514225,0.796333,0.597643,1.000000,0.912433,0.997606
Discount_Amount,-0.163583,-0.550380,0.805277,0.796319,0.912433,1.000000,0.881947
Final_Amount,-0.253864,-0.499274,0.781131,0.553793,0.997606,0.881947,1.000000

In [46]:
df["Quantity"].corr(df["Revenue"])

np.float64(-0.5142251269420186)

In [47]:
df["Price"].corr(df["Revenue"])

np.float64(0.7963331828105006)

In [48]:
df["Discount"].corr(df["Revenue"])

np.float64(0.5976432539323984)

In [49]:
df["Revenue"].corr(df["Final_Amount"])

np.float64(0.9976057315057875)

# Advanced GroupBy & Aggregation

## Why Use Multiple Aggregations?

In real-world data analysis, managers rarely need just one statistic.

Instead of calculating the total revenue, average revenue, maximum revenue, and order count separately, we can generate all these metrics in a single summary table using the `agg()` function.

This makes reports more efficient, readable, and suitable for business decision-making.

In [53]:
category_summary = (
    df.groupby("Category")
      .agg(
          Total_Revenue=("Revenue", "sum"),
          Average_Revenue=("Revenue", "mean"),
          Maximum_Revenue=("Revenue", "max"),
          Minimum_Revenue=("Revenue", "min"),
          Total_Orders=("Order_ID", "count")
      )
)
category_summary

,Total_Revenue,Average_Revenue,Maximum_Revenue,Minimum_Revenue,Total_Orders
Category,,,,,
Clothing,51900,8650.000000,17500,5600,6
Electronics,392000,56000.000000,100000,22000,7
Furniture,274000,39142.857143,55000,28000,7

In [54]:
category_summary.sort_values(
    by="Total_Revenue",
    ascending=False
)

,Total_Revenue,Average_Revenue,Maximum_Revenue,Minimum_Revenue,Total_Orders
Category,,,,,
Electronics,392000,56000.000000,100000,22000,7
Furniture,274000,39142.857143,55000,28000,7
Clothing,51900,8650.000000,17500,5600,6

In [55]:
region_summary = (
    df.groupby("Region")
      .agg(
          Total_Revenue=("Revenue", "sum"),
          Average_Revenue=("Revenue", "mean"),
          Orders=("Order_ID", "count"),
          Average_Discount=("Discount", "mean")
      )
)
region_summary

        Total_Revenue  Average_Revenue  Orders  Average_Discount
Region
East           218800          43760.0       5               8.4
North          201500          40300.0       5               9.0
South          159000          31800.0       5               8.6
West           138600          27720.0       5              10.0

In [57]:
df.groupby(
    ["Region", "Category"]
).agg(
    Revenue=("Revenue", "sum"),
    Orders=("Order_ID", "count")
)

                    Revenue  Orders
Region Category
East   Clothing       16800       2
       Electronics   166000       2
       Furniture      36000       1
North  Clothing       17500       1
       Electronics   124000       2
       Furniture      60000       2
South  Clothing        6000       1
       Electronics    80000       2
       Furniture      73000       2
West   Clothing       11600       2
       Electronics    22000       1
       Furniture     105000       2

# Ranking & Top-N Analysis

## What is Ranking?

Ranking is the process of ordering data from highest to lowest (or vice versa) based on a specific metric.

Businesses often use ranking to identify:

- Top-selling products
- Best customers
- Highest revenue regions
- Best-performing salespeople
- Lowest-performing categories

Pandas provides functions like `nlargest()`, `nsmallest()`, and `sort_values()` to perform these analyses efficiently.

In [58]:
df.nlargest(5, "Revenue")

,Order_ID,Customer,Region,Category,Product,Salesperson,Quantity,Price,Discount,Order_Date,Revenue,Discount_Amount,Final_Amount
0,101,John,North,Electronics,Laptop,Amit,2,50000,10,2024-01-10,100000,10000.0,90000.0
2,103,Bob,East,Electronics,Phone,Raj,3,30000,15,2024-01-22,90000,13500.0,76500.0
14,115,Oscar,East,Electronics,Camera,Raj,2,38000,10,2024-05-27,76000,7600.0,68400.0
19,120,Tom,West,Furniture,Dining Table,Neha,1,55000,15,2024-07-18,55000,8250.0,46750.0
7,108,Henry,West,Furniture,Sofa,Neha,2,25000,20,2024-03-15,50000,10000.0,40000.0

In [59]:
df.nsmallest(5, "Revenue")

,Order_ID,Customer,Region,Category,Product,Salesperson,Quantity,Price,Discount,Order_Date,Revenue,Discount_Amount,Final_Amount
15,116,Peter,West,Clothing,Cap,Amit,7,800,0,2024-06-04,5600,0.0,5600.0
3,104,David,West,Clothing,T-Shirt,Amit,5,1200,0,2024-02-05,6000,0.0,6000.0
9,110,Jack,South,Clothing,Jacket,Amit,3,2000,0,2024-04-02,6000,0.0,6000.0
18,119,Sophia,East,Clothing,Shirt,Amit,4,1500,5,2024-07-08,6000,300.0,5700.0
6,107,Grace,East,Clothing,Jeans,Amit,6,1800,5,2024-03-08,10800,540.0,10260.0

In [61]:
customer_rank = (
    df.groupby("Customer")["Revenue"]
      .sum()
      .sort_values(ascending=False)
      .head(5)
)
customer_rank

Customer
John     100000
Bob       90000
Oscar     76000
Tom       55000
Henry     50000
Name: Revenue, dtype: int64

In [63]:
category_rank = (
    df.groupby("Category")["Revenue"]
      .sum()
      .sort_values(ascending=False)
)
category_rank

Category
Electronics    392000
Furniture      274000
Clothing        51900
Name: Revenue, dtype: int64